# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_flowbite.ipynb.

# %% auto 0
__all__ = ['flowbite_hdrs', 'flowbite_ftrs', 'Round', 'TextT', 'TextPresets', 'TextHeading', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6',
           'Subtitle', 'Q', 'Em', 'Strong', 'I', 'Small', 'Mark', 'Del', 'Ins', 'Sub', 'Sup', 'BlockquoteT',
           'Blockquote', 'Caption', 'Cite', 'Time', 'Address', 'Abbr', 'Dfn', 'KbdT', 'Kbd', 'Samp', 'Var', 'Figure',
           'Details', 'Summary', 'Data', 'S', 'U', 'Output', 'CodeSpan', 'Code', 'CodeBlock', 'ParagrafT', 'P', 'Meter',
           'ButtonColor', 'ButtonSize', 'ButtonOutline', 'ButtonT', 'Button', 'FlexT', 'BackgroundT', 'ContainerSize',
           'Container', 'Titled', 'Grid', 'DivFullySpaced', 'DivCentered', 'DivLAligned', 'DivRAligned', 'DivVStacked',
           'DivHStacked', 'DividerT', 'Divider', 'DividerSplit', 'DividerLine', 'Article', 'ArticleTitle',
           'ArticleMeta', 'Icon', 'DiceBearAvatar', 'PicSumImg', 'SectionT', 'Section', 'TabItem', 'TabContainer',
           'FormT', 'Form', 'LabelInputT', 'InputT', 'Input', 'TextArea', 'Options', 'Select', 'RadioT', 'Radio',
           'CheckboxT', 'Checkbox', 'SwitchT', 'Switch', 'Upload']

# %% ../nbs/01_flowbite.ipynb 1
import fasthtml.common as fh
from .core import *
from fasthtml.common import Div, Span, FT, HighlightJS
from typing import Union, Tuple, Optional, Sequence
from fastcore.all import *
from enum import Enum, auto
# from mistletoe.html_renderer import HTMLRenderer
# from mistletoe.span_token import Image
# import mistletoe
# from lxml import html, etree

# %% ../nbs/01_flowbite.ipynb 2
flowbite_hdrs = (
    Script(src="https://unpkg.com/@tailwindcss/browser@4"),
    Link(
        rel="stylesheet",
        href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css",
    ),    
    Script(
        "if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\r\n        document.documentElement.classList.add('dark');\r\n    } else {\r\n        document.documentElement.classList.remove('dark')\r\n    }"
    ),
)

flowbite_ftrs = [
    Script(src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"),
    Script("""
    document.addEventListener('DOMContentLoaded', function() {
        // Get references to elements
        const drawerButton = document.querySelector('[data-drawer-target="logo-sidebar"]');
        const sidebar = document.getElementById('logo-sidebar');
        const mainContent = document.querySelector('.p-4:not(.mt-14)');
        
        // Function to toggle main content margin
        function toggleMainMargin() {
            // Check if sidebar is visible (doesn't have -translate-x-full class)
            if (!sidebar.classList.contains('-translate-x-full')) {
                // Sidebar is visible, add margin to main content
                mainContent.classList.add('ml-64');
            } else {
                // Sidebar is hidden, remove margin from main content
                mainContent.classList.remove('ml-64');
            }
        }
        
        // Initial check
        toggleMainMargin();
        
        // Listen for sidebar visibility changes
        if (drawerButton) {
            drawerButton.addEventListener('click', function() {
                // Wait for the drawer animation to complete
                setTimeout(toggleMainMargin, 300);
            });
        }
        
        // Create a MutationObserver to watch for class changes on the sidebar
        const observer = new MutationObserver(function(mutations) {
            mutations.forEach(function(mutation) {
                if (mutation.attributeName === 'class') {
                    toggleMainMargin();
                }
            });
        });
        
        // Start observing the sidebar for class changes
        if (sidebar) {
            observer.observe(sidebar, { attributes: true });
        }
    });
    """),
    Script("""
    var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
        var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

        // Change the icons inside the button based on previous settings
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            themeToggleLightIcon.classList.remove('hidden');
        } else {
            themeToggleDarkIcon.classList.remove('hidden');
        }

        var themeToggleBtn = document.getElementById('theme-toggle');

        themeToggleBtn.addEventListener('click', function() {

            // toggle icons inside button
            themeToggleDarkIcon.classList.toggle('hidden');
            themeToggleLightIcon.classList.toggle('hidden');

            // if set via local storage previously
            if (localStorage.getItem('color-theme')) {
                if (localStorage.getItem('color-theme') === 'light') {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                } else {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                }

            // if NOT set via local storage previously
            } else {
                if (document.documentElement.classList.contains('dark')) {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                } else {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                }
            }

        });
    """)
]

# %% ../nbs/01_flowbite.ipynb 3
class Round(VEnum):
    """Button shape variants"""
    default = "rounded-lg"
    full = "rounded-full"
    none = "rounded-none"
    sm = "rounded-sm"
    md = "rounded-md"
    lg = "rounded-lg"
    xl = "rounded-xl"
    _2xl = "rounded-2xl"
    _3xl = "rounded-3xl"
    _4xl = "rounded-4xl"

class TextT(VEnum):
    """
    Text Styles from Flowbite UI
    """
    
    # Text Size
    xs, sm, base, lg, xl = 'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl'
    text_2xl, text_3xl, text_4xl = 'text-2xl', 'text-3xl', 'text-4xl'
    text_5xl, text_6xl, text_7xl = 'text-5xl', 'text-6xl', 'text-7xl'
    text_8xl, text_9xl = 'text-8xl', 'text-9xl'
    
    # Text Weight
    thin, extralight, light = 'font-thin', 'font-extralight', 'font-light'
    normal, medium, semibold = 'font-normal', 'font-medium', 'font-semibold'
    bold, extrabold, black = 'font-bold', 'font-extrabold', 'font-black'
    
    # Text Style
    italic = 'italic'
    
    # Text Format
    article='format format-sm sm:format-base lg:format-lg format-primary dark:format-invert'
    # Text Color
    gray = 'text-gray-500 dark:text-gray-400'
    muted = 'text-gray-500 dark:text-gray-400'
    primary = 'text-primary-600 dark:text-primary-500'
    # TODO: Add secondary color
    secondary = 'text-purple-600 dark:text-purple-500'
    success = 'text-green-500 dark:text-green-400'
    warning = 'text-yellow-500 dark:text-yellow-400'
    error = 'text-red-600 dark:text-red-500'
    info = 'text-blue-500 dark:text-blue-400'
    
    # Text Alignment
    left, right, center = 'text-left', 'text-right', 'text-center'
    justify, start, end = 'text-justify', 'text-start', 'text-end'
    
    # Vertical Alignment
    top, middle, bottom = 'align-top', 'align-middle', 'align-bottom'
    
    # Text Decoration
    underline, line_through = 'underline', 'line-through'
    uppercase, lowercase = 'uppercase', 'lowercase'
    capitalize, normal_case = 'capitalize', 'normal-case'
    
    # Line Height
    leading_none = 'leading-none'
    leading_tight = 'leading-tight'
    leading_snug = 'leading-snug'
    leading_normal = 'leading-normal'
    leading_relaxed = 'leading-relaxed'
    leading_loose = 'leading-loose'
    
    # Letter Spacing
    tracking_tighter = 'tracking-tighter'
    tracking_tight = 'tracking-tight'
    tracking_normal = 'tracking-normal'
    tracking_wide = 'tracking-wide'
    tracking_wider = 'tracking-wider'
    tracking_widest = 'tracking-widest'
    
    # Text Wrapping
    truncate = 'truncate'
    whitespace_normal = 'whitespace-normal'
    whitespace_nowrap = 'whitespace-nowrap'
    whitespace_pre = 'whitespace-pre'
    whitespace_pre_line = 'whitespace-pre-line'
    whitespace_pre_wrap = 'whitespace-pre-wrap'
    
    # Other
    highlight = 'bg-yellow-200 dark:bg-yellow-800 text-black'

class TextPresets(VEnum):
    """
    Common Typography Presets for Flowbite UI
    """
    muted_sm = TextT.muted+TextT.sm
    muted_lg = TextT.muted+TextT.lg
    
    bold_sm = TextT.bold+TextT.sm
    bold_lg = TextT.bold+TextT.lg
    
    primary_bold = stringify((TextT.primary, TextT.bold))
    success_bold = stringify((TextT.success, TextT.bold))
    warning_bold = stringify((TextT.warning, TextT.bold))
    error_bold = stringify((TextT.error, TextT.bold))
    
    md_weight_sm = stringify((TextT.sm, TextT.medium))
    md_weight_muted = stringify((TextT.medium, TextT.muted))

class TextHeading(VEnum):
    """Text heading variants for Flowbite components"""
    h1 = "text-5xl font-extrabold dark:text-white mb-4"
    h2 = "text-4xl font-bold dark:text-white mb-3"
    h3 = "text-3xl font-bold dark:text-white mb-2"
    h4 = "text-2xl font-bold dark:text-white mb-1"
    h5 = "text-xl font-bold dark:text-white mb-0.5"
    h6 = "text-lg font-bold dark:text-white"

def H1(*c:FT|str, # Contents of H1 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H1 styling
       **kwargs # Additional args for H1 tag
       )->FT: # H1(..., cls='uk-h1')
    "H1 with styling and appropriate size"
    return fh.H1(*c, cls=(TextHeading.h1, stringify(cls)), **kwargs)

def H2(*c:FT|str, # Contents of H2 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H2 styling
       **kwargs # Additional args for H2 tag
       )->FT: # H2(..., cls='uk-h2')
    "H2 with styling and appropriate size"
    return fh.H2(*c, cls=(TextHeading.h2, stringify(cls)), **kwargs)

def H3(*c:FT|str, # Contents of H3 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H3 styling
       **kwargs # Additional args for H3 tag
       )->FT: # H3(..., cls='uk-h3')
    "H3 with styling and appropriate size"
    return fh.H3(*c, cls=(TextHeading.h3, stringify(cls)), **kwargs)

def H4(*c:FT|str, # Contents of H4 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H4 styling
       **kwargs # Additional args for H4 tag
       )->FT: # H4(..., cls='uk-h4')
    "H4 with styling and appropriate size"
    return fh.H4(*c, cls=(TextHeading.h4, stringify(cls)), **kwargs)

def H5(*c:FT|str, # Contents of H5 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H5 styling
       **kwargs # Additional args for H5 tag
       )->FT: # H5(..., cls='uk-h5')
    "H5 with styling and appropriate size"
    return fh.H5(*c, cls=(TextHeading.h5, stringify(cls)), **kwargs)

def H6(*c:FT|str, # Contents of H6 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H6 styling
       **kwargs # Additional args for H6 tag
       )->FT: # H6(..., cls='uk-h6')
    "H6 with styling and appropriate size"
    return fh.H6(*c, cls=(TextHeading.h6, stringify(cls)), **kwargs)


def Subtitle(*c:FT|str, # Contents of P tag (often text)
         cls:Enum|str|tuple='mt-1.5', # Additional classes
         **kwargs # Additional args for P tag
         )->FT:
    "Styled muted_sm text designed to go under Headings and Titles"
    return fh.P(*c, cls=(TextPresets.muted_sm, stringify(cls)), **kwargs)


def Q(*c:FT|str, # Contents of Q tag (quote)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for Q tag
      )->FT:
    "Styled quotation mark"
    return fh.Q(*c, cls=(TextT.italic,TextT.lg, stringify(cls)), **kwargs)

def Em(*c:FT|str, # Contents of Em tag (emphasis)
       cls:Enum|str|tuple=(), # Additional classes 
       **kwargs # Additional args for Em tag
       )->FT:
    "Styled emphasis text"
    return fh.Em(*c, cls=(TextT.medium, stringify(cls)), **kwargs)

def Strong(*c:FT|str, # Contents of Strong tag
          cls:Enum|str|tuple=(), # Additional classes
          **kwargs # Additional args for Strong tag
          )->FT:
    "Styled strong text" 
    return fh.Strong(*c, cls=(TextT.bold, stringify(cls)), **kwargs)

def I(*c:FT|str, # Contents of I tag (italics)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for I tag
      )->FT:
    "Styled italic text"
    return fh.I(*c, cls=(TextT.italic, stringify(cls)), **kwargs)

def Small(*c:FT|str, # Contents of Small tag
         cls:Enum|str|tuple=(), # Additional classes
         **kwargs # Additional args for Small tag
         )->FT:
    "Styled small text"
    return fh.Small(*c, cls=(TextT.sm, stringify(cls)), **kwargs)

def Mark(*c:FT|str, # Contents of Mark tag (highlighted text)
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Mark tag
        )->FT:
    "Styled highlighted text"
    return fh.Mark(*c, cls=(TextT.highlight, stringify(cls)), **kwargs)


def Del(*c:FT|str, # Contents of Del tag (deleted text)
       cls:Enum|str|tuple=(), # Additional classes
       **kwargs # Additional args for Del tag
       )->FT:
    "Styled deleted text"
    return fh.Del(*c, cls=('line-through', TextT.gray, stringify(cls)), **kwargs)

def Ins(*c:FT|str, # Contents of Ins tag (inserted text)
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Ins tag
        )->FT:
    "Styled inserted text"
    return fh.Ins(*c, cls=(TextT.underline+' text-green-600', stringify(cls)), **kwargs)

def Sub(*c:FT|str, # Contents of Sub tag (subscript)
       cls:Enum|str|tuple=(), # Additional classes
       **kwargs # Additional args for Sub tag
       )->FT:
    "Styled subscript text"
    return fh.Sub(*c, cls=(TextT.sm+' -bottom-1 relative', stringify(cls)), **kwargs)

def Sup(*c:FT|str, # Contents of Sup tag (superscript) 
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Sup tag
        )->FT:
    "Styled superscript text"
    return fh.Sup(*c, cls=(TextT.sm+' -top-1 relative', stringify(cls)), **kwargs)

class BlockquoteT(VEnum):
    """Blockquote variants"""
    default = "italic font-semibold text-gray-900 dark:text-white p-4 my-4"
    solid = "italic font-semibold text-gray-900 dark:text-white p-4 my-4 border-s-4 border-gray-300 bg-gray-50 dark:border-gray-500 dark:bg-gray-800"
    secondary = "border-l-4 border-gray-300 dark:border-gray-500"
    success = "border-l-4 border-green-500"
    

def Blockquote(*c:FT|str, # Contents of Blockquote tag (often text)
               with_icon:bool=False,
               cls:Enum|str|tuple=BlockquoteT.default, # Classes in addition to Blockquote styling
               **kwargs # Additional args for Blockquote tag
               )->FT: # Blockquote(..., cls='uk-blockquote')
    "Blockquote with Styling"
    elements =[]
    if with_icon:
        elements.append(Icon("quote",cls="h-8 w-8 text-gray-400 dark:text-gray-600 mb-1"))
    elements.append(*c)
    return fh.Blockquote(*elements, cls=(stringify(cls)), **kwargs)


def Caption(*c:FT|str, cls:Enum|str|tuple=(), **kwargs)->FT:
    "Styled caption text"
    return fh.Caption(
        Span(*c, cls=(TextT.gray, TextT.sm, stringify(cls))),
        **kwargs)


def Cite(*c:FT|str, # Contents of Cite tag
         cls:Enum|str|tuple=(), # Additional classes
         **kwargs # Additional args for Cite tag
         )->FT:
    "Styled citation text"
    return fh.Cite(*c, cls=(TextT.italic, TextT.gray, stringify(cls)), **kwargs)

def Time(*c:FT|str, # Contents of Time tag
         cls:Enum|str|tuple=(), # Additional classes
         datetime:str=None, # datetime attribute
         **kwargs # Additional args for Time tag
         )->FT:
    "Styled time element"
    if datetime: kwargs['datetime'] = datetime
    return fh.Time(*c, cls=(TextT.gray, stringify(cls)), **kwargs)

def Address(*c:FT|str, # Contents of Address tag
           cls:Enum|str|tuple=(), # Additional classes
           **kwargs # Additional args for Address tag
           )->FT:
    "Styled address element"
    return fh.Address(*c, cls=(TextT.italic, stringify(cls)), **kwargs)


def Abbr(*c:FT|str, # Contents of Abbr tag
         cls:Enum|str|tuple=(), # Additional classes
         title:str=None, # Title attribute for abbreviation
         **kwargs # Additional args for Abbr tag
         )->FT:
    "Styled abbreviation with dotted underline"
    if title: kwargs['title'] = title
    return fh.Abbr(*c, cls=('border-b border-dotted border-gray-300 dark:border-gray-500 hover:cursor-help', stringify(cls)), **kwargs)

def Dfn(*c:FT|str, # Contents of Dfn tag (definition)
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Dfn tag
        )->FT:
    "Styled definition term with italic and medium weight"
    return fh.Dfn(*c, cls=(TextT.medium + TextT.italic + TextT.gray, stringify(cls)), **kwargs)

class KbdT(VEnum):
    """Keyboard input variants"""
    default = "font-mono px-1.5 py-0.5 text-sm bg-gray-200 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded shadow-sm"
    advanced = "px-2 py-1.5 text-xs font-semibold text-gray-800 bg-gray-100 border border-gray-200 rounded-lg dark:bg-gray-600 dark:text-gray-100 dark:border-gray-500"

def Kbd(*c:FT|str, # Contents of Kbd tag (keyboard input)
        cls:Enum|str|tuple=KbdT.default, # Additional classes
        **kwargs # Additional args for Kbd tag
        )->FT:
    "Styled keyboard input with subtle background"
    return fh.Kbd(*c, cls=stringify(cls), **kwargs)


def Samp(*c:FT|str, # Contents of Samp tag (sample output)
         cls:Enum|str|tuple=(), # Additional classes
         **kwargs # Additional args for Samp tag
         )->FT:
    "Styled sample output with subtle background"
    return fh.Samp(*c, cls=('font-mono bg-gray-200 dark:bg-gray-800 px-1 rounded', TextT.gray, stringify(cls)), **kwargs)

def Var(*c:FT|str, # Contents of Var tag (variable)
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Var tag
        )->FT:
    "Styled variable with italic monospace"
    return fh.Var(*c, cls=('font-mono',TextT.italic + TextT.gray, stringify(cls)), **kwargs)


def Figure(*c:FT|str, # Contents of Figure tag
          cls:Enum|str|tuple=(), # Additional classes 
          **kwargs # Additional args for Figure tag
          )->FT:
    "Styled figure container with card-like appearance"
    return fh.Figure(*c, cls=('p-4 my-4 border border-gray-200 dark:border-gray-800 rounded-lg shadow-sm bg-gray-200 dark:bg-gray-800', stringify(cls)), **kwargs)


def Details(*c:FT|str, # Contents of Details tag
           cls:Enum|str|tuple=(), # Additional classes
           **kwargs # Additional args for Details tag
           )->FT:
    "Styled details element"
    # TODO: Add secondary color variant
    return fh.Details(*c, cls=('border border-gray-200 dark:border-gray-800 rounded-lg', stringify(cls)), **kwargs)

def Summary(*c:FT|str, # Contents of Summary tag
           cls:Enum|str|tuple=(), # Additional classes
           **kwargs # Additional args for Summary tag
           )->FT:
    "Styled summary element"
    return fh.Summary(*c, cls=(TextT.medium + ' p-3 hover:bg-gray-200 dark:hover:bg-gray-800 cursor-pointer', stringify(cls)), **kwargs)

def Data(*c:FT|str, # Contents of Data tag
         value:str=None, # Value attribute
         cls:Enum|str|tuple=(), # Additional classes
         **kwargs # Additional args for Data tag
         )->FT:
    "Styled data element"
    if value: kwargs['value'] = value
    return fh.Data(*c, cls=('font-mono text-sm bg-gray-200 dark:bg-gray-800 px-1 rounded', stringify(cls)), **kwargs)


def S(*c:FT|str, # Contents of S tag (strikethrough)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for S tag
      )->FT:
    "Styled strikethrough text (different semantic meaning from Del)"
    return fh.S(*c, cls=('line-through', TextT.gray, stringify(cls)), **kwargs)

def U(*c:FT|str, # Contents of U tag (unarticulated annotation)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for U tag
      )->FT:
    "Styled underline (for proper names in Chinese, proper spelling etc)"
    return fh.U(*c, cls=(TextT.underline, stringify(cls)), **kwargs)

def Output(*c:FT|str, # Contents of Output tag
          form:str=None, # ID of form this output belongs to
          for_:str=None, # IDs of elements this output is for
          cls:Enum|str|tuple=(), # Additional classes
          **kwargs # Additional args for Output tag
          )->FT:
    "Styled output element for form results"
    if form: kwargs['form'] = form
    if for_: kwargs['for'] = for_  # Note: 'for' is reserved in Python
    return fh.Output(*c, cls=('font-mono bg-gray-200 dark:bg-gray-800 px-2 py-1 rounded', 
                             stringify(cls)), **kwargs)

# %% ../nbs/01_flowbite.ipynb 4
def CodeSpan(*c, # Contents of CodeSpan tag (inline text code snippets)
             cls="text-sm text-primary-800 dark:text-primary-400 bg-tw-format-code-bg", # Classes in addition to CodeSpan styling
             **kwargs # Additional args for CodeSpan tag
             )->FT: # Code(..., cls='uk-codespan')
    "A CodeSpan with Styling"
    return fh.Code(*c, cls=(stringify(cls)), **kwargs)

def Code(*c, # Contents of CodeSpan tag (inline text code snippets)
             cls="text-sm text-primary-800 dark:text-primary-400 bg-tw-format-code-bg", # Classes in addition to CodeSpan styling
             **kwargs # Additional args for CodeSpan tag
             )->FT: # Code(..., cls='uk-codespan')
    "A Code with Styling"
    return fh.Code(*c, cls=(stringify(cls)), **kwargs)

def CodeBlock(*c: str, # Contents of Code tag (often text)
              cls: Enum | str | tuple = (), # Classes for the outer container
              code_cls: Enum | str | tuple = "'overflow-scroll max-h-full'", # Classes for the code tag
              **kwargs # Additional args for Code tag
              ) -> FT: # Div(Pre(Code(..., cls='uk-codeblock), cls='multiple tailwind styles'), cls='uk-block')
    "CodeBlock with Styling"
    return Div(
        Pre(Code(*c, cls=(stringify(code_cls)), **kwargs),
            cls=(f'bg-gray-100 dark:bg-gray-800 {TextT.gray} p-0.4 rounded text-sm font-mono')),
#             cls=('bg-gray-100 dark:bg-gray-800 dark:text-gray-200 p-0.4 rounded text-sm font-mono'))
        cls=(Round.lg, stringify(cls)))

class ParagrafT(VEnum):
    default = TextT.gray+"my-3"
    lead = TextT.gray+"my-3 text-lg md:text-xl"
    capital_first = "my-3 text-gray-500 dark:text-gray-400 first-line:uppercase first-line:tracking-widest first-letter:text-7xl first-letter:font-bold first-letter:text-gray-900 dark:first-letter:text-gray-100 first-letter:me-3 first-letter:float-start"
    link = "my-3 font-medium text-primary-600 underline dark:text-primary-500 dark:hover:text-primary-600 hover:text-primary-700 hover:no-underline"
    primary = TextT.primary+"my-3"
    secondary = TextT.secondary+"my-3"
    xs = TextT.xs+"my-3"
    sm = TextT.sm+"my-3"

def P(*c, # Contents of P tag (often text)
      cls=ParagrafT.default, # Classes in addition to P styling
      **kwargs # Additional args for P tag
      )->FT: # P(..., cls='uk-p')
    "A P with Styling"
    return fh.Div(fh.P(*c, cls=(stringify(cls)), **kwargs))

# %% ../nbs/01_flowbite.ipynb 5
def Meter(*c:FT|str, # Contents of Meter tag
          value:float=None, # Current value
          min:float=None, # Minimum value
          max:float=None, # Maximum value
          cls:Enum|str|tuple=(), # Additional classes
          **kwargs # Additional args for Meter tag
          )->FT:
    "Styled meter element"
    if value is not None: kwargs['value'] = value
    if min is not None: kwargs['min'] = min
    if max is not None: kwargs['max'] = max
    return fh.Meter(*c, cls=('w-full h-2 rounded', stringify(cls)), **kwargs)

# %% ../nbs/01_flowbite.ipynb 6
class ButtonColor(VEnum):
    """Button style variants for Flowbite components"""
    # Base styles
    primary = "bg-primary-700 hover:bg-primary-800 dark:bg-primary-600 dark:hover:bg-primary-700  text-white focus:ring-primary-300 dark:focus:ring-primary-800"
    blue = "bg-blue-700 hover:bg-blue-800 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 text-white focus:ring-blue-300"
    green = "bg-green-700 hover:bg-green-800 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 text-white focus:ring-green-300"
    cyan = "bg-cyan-700 hover:bg-cyan-800 dark:bg-cyan-600 dark:hover:bg-cyan-700 dark:focus:ring-cyan-800 text-white focus:ring-cyan-300"
    teal = "bg-teal-700 hover:bg-teal-800 dark:bg-teal-600 dark:hover:bg-teal-700 dark:focus:ring-teal-800 text-white focus:ring-teal-300"
    lime = "bg-lime-700 hover:bg-lime-800 dark:bg-lime-600 dark:hover:bg-lime-700 dark:focus:ring-lime-800 text-white focus:ring-lime-300"
    red = "bg-red-700 hover:bg-red-800 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 text-white focus:ring-red-300"
    yellow = "bg-yellow-400 hover:bg-yellow-500 dark:focus:ring-yellow-900 text-white focus:ring-yellow-300"
    pink = "bg-pink-700 hover:bg-pink-800 dark:bg-pink-600 dark:hover:bg-pink-700 dark:focus:ring-pink-900 text-white focus:ring-pink-300"
    purple = "bg-purple-700 hover:bg-purple-800 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900 text-white focus:ring-purple-300"
    
    grad_primary = "text-white bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-primary-300 dark:focus:ring-primary-800"
    grad_blue = "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
    grad_green = "text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800"
    grad_cyan = "text-white bg-gradient-to-r from-cyan-500 via-cyan-600 to-cyan-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800"
    grad_teal = "text-white bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 dark:focus:ring-teal-800"
    grad_lime = "text-white bg-gradient-to-r from-lime-500 via-lime-600 to-lime-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800"
    grad_red = "text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800"
    grad_yellow = "text-white bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-yellow-300 dark:focus:ring-yellow-800"
    grad_pink = "text-white bg-gradient-to-r from-pink-500 via-pink-600 to-pink-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800"
    grad_purple = "text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800"
    #Duotone
    purple_blue = "text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
    cyan_blue = "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800"
    green_blue = "text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800"
    purple_pink = "text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800"
    pink_orange = "text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
    teal_lime = "text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-teal-700"
    red_yellow = "text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400"

class ButtonSize(VEnum):
    """Button size variants"""
    xs = "px-3 py-2 text-xs font-medium"
    sm = "px-3 py-2 text-sm font-medium"
    base = "px-5 py-2.5 text-sm font-medium"
    lg = "px-5 py-3 text-base font-medium"
    xl = "px-6 py-3.5 text-base font-medium"
    
class ButtonOutline(VEnum):
    """Button outline variants"""
    default = "border border-blue-700 hover:bg-blue-800 dark:border-blue-500 dark:hover:bg-blue-500 text-blue-700 hover:text-white dark:text-blue-500 dark:hover:text-white focus:ring-blue-300 dark:focus:ring-blue-800"
    dark = "border border-gray-800 hover:bg-gray-900 dark:border-gray-600 dark:hover:bg-gray-600 text-gray-900 hover:text-white dark:text-gray-400 dark:hover:text-white focus:ring-gray-300 dark:focus:ring-gray-800"
    green = "border border-green-700 hover:bg-green-800 dark:border-green-500 dark:hover:bg-green-600 text-green-700 hover:text-white dark:text-green-500 dark:hover:text-white focus:ring-green-300 dark:focus:ring-green-800"
    red = "border border-red-700 hover:bg-red-800 dark:border-red-500 dark:hover:bg-red-600 text-red-700 hover:text-white dark:text-red-500 dark:hover:text-white focus:ring-red-300 dark:focus:ring-red-900"
    yellow = "border border-yellow-400 hover:bg-yellow-500 dark:border-yellow-300 dark:hover:bg-yellow-400 text-yellow-400 hover:text-white dark:text-yellow-300 dark:hover:text-white focus:ring-yellow-300 dark:focus:ring-yellow-900"
    purple = "border border-purple-700 hover:bg-purple-800 dark:border-purple-400 dark:hover:bg-purple-500 text-purple-700 hover:text-white dark:text-purple-400 dark:hover:text-white focus:ring-purple-300 dark:focus:ring-purple-900"

class ButtonT(VEnum):
    """Button type variants"""
    primary = ButtonColor.primary.value
    secondary = "bg-white border border-gray-300 hover:bg-gray-100 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 text-gray-900 focus:ring-gray-200 dark:focus:ring-gray-700"
    ghost = "hover:bg-gray-100 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-gray-300 dark:focus:ring-gray-700 cursor-pointer"
    link = "dark:text-white cursor-pointer"
    success = ButtonColor.green.value   
    warning = ButtonColor.yellow.value
    error = ButtonColor.red.value
    info = ButtonColor.blue.value

# %% ../nbs/01_flowbite.ipynb 7
def Button(*c: Union[str, FT],cls: Union[str, Enum]=ButtonT.primary, shape: Union[str, Enum]=Round.default, size: Union[str, Enum]=ButtonSize.base, submit=True, **kwargs) -> FT: 
    base_class = "text-center inline-flex items-center"
    if 'type' not in kwargs: kwargs['type'] = 'submit' if submit else 'button'
    return fh.Button(*c, cls=(base_class, stringify(shape), stringify(cls), stringify(size)), **kwargs)

# %% ../nbs/01_flowbite.ipynb 8
class FlexT(VEnum):
    'Flexbox modifiers using Tailwind CSS'
    def _generate_next_value_(name, start, count, last_values): return name
    
    # Display
    block = 'flex'
    inline = 'inline-flex'
    
    # Horizontal Alignment
    left = 'justify-start' 
    center = 'justify-center'
    right = 'justify-end'
    between = 'justify-between'
    around = 'justify-around'
    
    # Vertical Alignment
    stretch = 'items-stretch'
    top = 'items-start'
    middle = 'items-center' 
    bottom = 'items-end'
    
    # Direction
    row = 'flex-row'
    row_reverse = 'flex-row-reverse'
    column = 'flex-col'
    column_reverse = 'flex-col-reverse'
    
    # Wrap
    nowrap = 'flex-nowrap'
    wrap = 'flex-wrap'
    wrap_reverse = 'flex-wrap-reverse'

class BackgroundT(VEnum):
    primary = "bg-primary-100 dark:bg-primary-800"
    secondary = "bg-gray-100 dark:bg-gray-800"
    success = "bg-green-100 dark:bg-green-800"
    warning = "bg-yellow-100 dark:bg-yellow-800"
    error = "bg-red-100 dark:bg-red-800"
    info = "bg-blue-100 dark:bg-blue-800"

    hover_primary = "bg-primary-100 dark:bg-primary-800 hover:bg-primary-200 dark:hover:bg-primary-700"
    hover_secondary = "bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700"
    hover_success = "bg-green-100 dark:bg-green-800 hover:bg-green-200 dark:hover:bg-green-700"
    hover_warning = "bg-yellow-100 dark:bg-yellow-800 hover:bg-yellow-200 dark:hover:bg-yellow-700"
    hover_error = "bg-red-100 dark:bg-red-800 hover:bg-red-200 dark:hover:bg-red-700"
    hover_info = "bg-blue-100 dark:bg-blue-800 hover:bg-blue-200 dark:hover:bg-blue-700"
    
    grad_primary = "bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 hover:bg-gradient-to-br"
    grad_secondary = "bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br"
    grad_success = "bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br"
    grad_warning = "bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br"
    grad_error = "bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br"
    grad_info = "bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br"
    grad_blue = "bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br"
    grad_green = "bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br"
    grad_cyan = "bg-gradient-to-r from-cyan-500 via-cyan-600 to-cyan-700 hover:bg-gradient-to-br"
    grad_teal = "bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700 hover:bg-gradient-to-br"
    grad_lime = "bg-gradient-to-r from-lime-500 via-lime-600 to-lime-700 hover:bg-gradient-to-br"
    grad_red = "bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br"
    grad_yellow = "bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br"
    grad_pink = "bg-gradient-to-r from-pink-500 via-pink-600 to-pink-700 hover:bg-gradient-to-br"
    grad_purple = "bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br"
    #Duotone
    purple_blue = "bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl"
    cyan_blue = "bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl"
    green_blue = "bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl"
    purple_pink = "bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l"
    pink_orange = "bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl"
    teal_lime = "bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200"
    red_yellow = "bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl"

# %% ../nbs/01_flowbite.ipynb 9
class ContainerSize(VEnum):
    """Container size variants for Flowbite components"""
    # Base container with responsive padding
    default = "container mx-auto"    
    # Fixed width containers based on Flowbite size variables
    # These add mx-auto to center and have responsive padding
    _3xs = "max-w-3xs" # --container-3xs:16rem
    _2xs = "max-w-2xs" # --container-2xs:18rem
    xs = "max-w-xs"  # --container-xs:20rem
    sm = "max-w-sm"  # --container-sm:24rem
    md = "max-w-md"  # --container-md:28rem
    lg = "max-w-lg"  # --container-lg:32rem
    xl = "max-w-xl"  # --container-xl:36rem
    _2xl = "max-w-2xl" # --container-2xl:42rem
    _3xl = "max-w-3xl" # --container-3xl:48rem
    _4xl = "max-w-4xl" # --container-4xl:56rem
    _5xl = "max-w-5xl" # --container-5xl:64rem
    _6xl = "max-w-6xl" # --container-6xl:72rem
    _7xl = "max-w-7xl" # --container-7xl:80rem
    
    # Special container types
    fluid = "w-full px-4"  # Full width with padding
    responsive = "w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl 2xl:max-w-2xl px-4"  # Responsive sizing

def Container(*c: Union[str, FT], 
            size: Union[str, Enum]=ContainerSize.default, 
            cls: Union[str, Enum, tuple]=(),
            **kwargs) -> FT:
    """
    Container component based on Flowbite container sizes.
    """
    all_cls = (stringify(size), stringify(cls))
    return Div(*c, cls=all_cls, **kwargs)

# %% ../nbs/01_flowbite.ipynb 10
def Titled(title:str="FastHTML app", # Title of the page
           *c, # Contents of the page (often other tags)
           cls=ContainerSize.xl, # Classes in addition to Container styling
           **kwargs # Additional args for Container (`Div` tag)
           )->FT: # Title, Main(Container(H1(title), content))
    "Creates a standard page structure for titled page.  Main(Container(title, content))"
    return fh.Title(title), fh.Main(Container(H1(title), *c, cls=cls, **kwargs))


# %% ../nbs/01_flowbite.ipynb 11
def Grid(*div, # `Div` components to put in the grid
         cols_min:int=1, # Minimum number of columns at any screen size
         cols_max:int=4, # Maximum number of columns allowed at any screen size
         cols_sm:int=None, # Number of columns on small screens
         cols_md:int=None, # Number of columns on medium screens
         cols_lg:int=None, # Number of columns on large screens
         cols_xl:int=None, # Number of columns on extra large screens
         cols:int=None, # Number of columns on all screens
         cls='gap-4', # Additional classes on the grid (tip: `gap` provides spacing for grids)
         **kwargs # Additional args for `Div` tag
         )->FT: # Responsive grid component
    "Creates a responsive grid layout with smart defaults based on content"
    n = len(div)
    
    if cols:
        # If cols is specified, use it for all breakpoints
        cols_min = cols_sm = cols_md = cols_lg = cols_xl = cols
    else:
        # Otherwise, calculate progressive defaults for each breakpoint
        cols_max = min(n, cols_max)
        cols_sm = cols_sm or min(2, n)                # Default to 2 columns for small screens
        cols_md = cols_md or min(3, n)                # Default to 3 columns for medium screens
        cols_lg = cols_lg or min(4, n, cols_max)      # Default to 4 columns for large screens
        cols_xl = cols_xl or min(cols_max, n)         # Default to cols_max for extra large screens
    
    grid_cls = f'grid grid-cols-{cols_min} sm:grid-cols-{cols_sm} md:grid-cols-{cols_md} lg:grid-cols-{cols_lg} xl:grid-cols-{cols_xl}'
    return Div(cls=(grid_cls, stringify(cls)), **kwargs)(*div)

def DivFullySpaced(*c,                # Components
                   cls='w-full',# Classes for outer div (`w-full` makes it use all available width)
                   **kwargs           # Additional args for outer div
                  ):                  # Div with spaced components via flex classes
    "Creates a flex div with it's components having as much space between them as possible"
    cls = stringify(cls)
    return Div(cls=(FlexT.block,FlexT.between,FlexT.middle,cls), **kwargs)(*c)

def DivCentered(*c,      # Components
                cls='space-y-4',  # Classes for outer div (`space-y-4` provides spacing between components)
                vstack=True, # Whether to stack the components vertically
                **kwargs # Additional args for outer div
               )->FT: # Div with components centered in it
    "Creates a flex div with it's components centered in it"
    cls=stringify(cls)
    return Div(cls=(FlexT.block,(FlexT.column if vstack else FlexT.row),FlexT.middle,FlexT.center,cls),**kwargs)(*c)

def DivLAligned(*c, # Components
                cls='space-x-4',  # Classes for outer div
                **kwargs # Additional args for outer div
               )->FT: # Div with components aligned to the left
    "Creates a flex div with it's components aligned to the left"
    cls=stringify(cls)
    return Div(cls=(FlexT.block,FlexT.left,FlexT.middle,cls), **kwargs)(*c)

def DivRAligned(*c, # Components
                cls='space-x-4',  # Classes for outer div
                **kwargs # Additional args for outer div
               )->FT: # Div with components aligned to the right
    "Creates a flex div with it's components aligned to the right"
    cls=stringify(cls)
    return Div(cls=(FlexT.block,FlexT.right,FlexT.middle,cls), **kwargs)(*c)

def DivVStacked(*c, # Components
                cls='space-y-4', # Additional classes on the div  (tip: `space-y-4` provides spacing between components)
                **kwargs # Additional args for the div
               )->FT: # Div with components stacked vertically
    "Creates a flex div with it's components stacked vertically"
    cls=stringify(cls)
    return Div(cls=(FlexT.block,FlexT.column,FlexT.middle,cls), **kwargs)(*c)

def DivHStacked(*c, # Components
                cls='space-x-4', # Additional classes on the div (`space-x-4` provides spacing between components)
                **kwargs # Additional args for the div
               )->FT: # Div with components stacked horizontally
    "Creates a flex div with it's components stacked horizontally"
    cls=stringify(cls)
    return Div(cls=(FlexT.block,FlexT.row,FlexT.middle,cls), **kwargs)(*c)
   

# %% ../nbs/01_flowbite.ipynb 13
class DividerT(VEnum):
    default = "h-px my-8 bg-gray-200 border-0 dark:bg-gray-600"
    vertical = "h-full w-px mx-4 bg-gray-200 border-0 dark:bg-gray-600"
    trimmed = "w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded-sm md:my-10 dark:bg-gray-600"
    trimmed_vertical = "h-48 w-1 my-auto mx-4 bg-gray-100 border-0 rounded-sm md:mx-10 dark:bg-gray-600"

def Divider(*c, # contents of Divider tag (often nothing)
            vertical=False, # Whether to create a vertical divider
            cls=(), # Classes in addition to Divider styling
            **kwargs # Additional args for Divider tag
            )->FT: #  Hr(..., cls='uk-divider-icon') or Div(..., cls='uk-divider-vertical')
    "Divider with default styling and margin"
    cls = (stringify(cls), DividerT.vertical) if vertical else (stringify(cls), DividerT.default)
    container = Div if vertical else Hr
    return container(*c, cls=cls, **kwargs)

# TODO: This is a copy of the DividerSplit function in fh_flowbite/components.py
def DividerSplit(*c, cls=(), line_cls=(), text_cls=()):
    "Creates a simple horizontal line divider with configurable thickness and vertical spacing"
    cls, line_cls, text_cls = map(stringify,(cls, line_cls, text_cls))
    return Div(
            Divider(cls='w-64 h-1 my-8 bg-gray-200 border-0 rounded-sm dark:bg-gray-700'),
            Div(
                *c,
                cls='absolute px-4 -translate-x-1/2 left-1/2 bg-inherit'
            ),
            cls='inline-flex items-center justify-center w-full'
        )


def DividerLine(lwidth=2, y_space=4): return Hr(cls=f"my-{y_space} h-[{lwidth}px] w-full bg-gray-200 dark:bg-gray-700")


# %% ../nbs/01_flowbite.ipynb 15
def Article(*c, # contents of Article tag (often other tags)
            cls=(), # Classes in addition to Article styling
            **kwargs # Additional args for Article tag
            )->FT: # Article(..., cls='uk-article')
    "A styled article container for blog posts or similar content"
    return fh.Article(*c, cls=(TextT.article,stringify(cls)), **kwargs)

def ArticleTitle(*c, # contents of ArticleTitle tag (often other tags)
                 cls=(), # Classes in addition to ArticleTitle styling
                 **kwargs # Additional args for ArticleTitle tag
                 )->FT: # H1(..., cls='uk-article-title')
    "A title component for use within an Article"
    return H1(*c, cls=(TextT.article,stringify(cls)), **kwargs)

def ArticleMeta(*c, # contents of ArticleMeta tag (often other tags)
                cls=(), # Classes in addition to ArticleMeta styling
                **kwargs # Additional args for ArticleMeta tag
                )->FT: # P(..., cls='uk-article-meta')
    "A metadata component for use within an Article showing things like date, author etc"
    return P(*c, cls=('text-base text-gray-500 dark:text-gray-400',stringify(cls)), **kwargs)


# %% ../nbs/01_flowbite.ipynb 16
def Icon(icon:str, # Icon name from [lucide icons](https://lucide.dev/icons/)
           height:int=None, 
           width:int=None, 
           stroke_width:int=None, # Thickness of lines
           cls=(), # Additional classes on the `Uk_icon` tag
           **kwargs # Additional args for `Uk_icon` tag
           )->FT: # a lucide icon of the specified size 
    "Creates an icon using lucide icons"
    return I(data_lucide=icon, height=height, width=width, stroke_width=stroke_width, cls=cls, **kwargs)

def DiceBearAvatar(seed_name:str, # Seed name (ie 'Isaac Flath')
                   h:int=12,         # Height 
                   w:int=12,  
                   cls:str=Round.full,
                   **kwargs # Additional args for the span
                  ):          # Span with Avatar
    "Creates an Avatar using https://dicebear.com/"
    url = 'https://api.dicebear.com/8.x/lorelei/svg?seed='
    return Span(cls=(stringify(cls),f"relative flex h-{h} w-{w} shrink-0 overflow-hidden bg-gray-200 dark:bg-gray-700"))(
            fh.Img(cls=f"aspect-square h-{h} w-{w}", alt="Avatar", loading="lazy", src=f"{url}{seed_name}", **kwargs))

def PicSumImg(h:int=200,           # Height in pixels
              w:int=200,           # Width in pixels
              id:int=None,        # Optional specific image ID to use
              grayscale:bool=False, # Whether to return grayscale version
              blur:int=None,       # Optional blur amount (1-10)
              **kwargs             # Additional args for Img tag
              )->FT:              # Img tag with picsum image
    "Creates a placeholder image using https://picsum.photos/"
    url = f"https://picsum.photos"
    if id is not None: url = f"{url}/id/{id}"
    url = f"{url}/{w}/{h}"
    if grayscale: url = f"{url}?grayscale"
    if blur is not None: 
        url = f"{url}{'?' if not grayscale else '&'}blur={max(1,min(10,blur))}"
    return fh.Img(src=url, loading="lazy", **kwargs)

# %% ../nbs/01_flowbite.ipynb 18
class SectionT(VEnum):
    default = "py-12 px-4"
    muted = BackgroundT.secondary+"py-12 px-4"
    primary = BackgroundT.primary+"py-12 px-4"
    secondary = BackgroundT.secondary+"py-12 px-4"
    xs = ContainerSize.xs+"py-12 px-4"
    sm = ContainerSize.sm+"py-12 px-4"
    lg = ContainerSize.lg+"py-12 px-4"
    xl = ContainerSize.xl+"py-12 px-4"

def Section(*c, # contents of Section tag (often other tags)
            cls=(), # Classes in addition to Section styling
            **kwargs # Additional args for Section tag
            )->FT: # Div(..., cls='uk-section')
    return fh.Section(*c, cls=(stringify(cls)), **kwargs)

# %% ../nbs/01_flowbite.ipynb 19
def TabItem(text:str, # Components
            controls:str, # Controls of the tab
            **kwargs # Additional args for the `Li`
           )->FT: # Tab item
    ctrl = f'{controls}' if controls else text
    "A TabItem where children will be different tabs"
    return Li(role='presentation', cls='me-2')(
            Button(text, id=f'{text}-tab', data_tabs_target=f'#{ctrl}', type='button', role='tab', aria_controls=ctrl, aria_selected='false', cls='inline-block p-4 border-b-2'+Round.none, **kwargs)
        )

def TabContainer(*li, # Components
                  cls='', # Additional classes on the `Ul`,
                  active_items_cls='text-primary-600 hover:text-primary-600 dark:text-primary-500 dark:hover:text-primary-500 border-primary-600 dark:border-primary-500', # Additional classes on the active items
                  inactive_items_cls='dark:border-transparent text-gray-500 hover:text-gray-600 dark:text-gray-400 border-gray-100 hover:border-gray-300 dark:border-gray-700 dark:hover:text-gray-300', # Additional classes on the inactive items
                  **kwargs # Additional args for the `Ul`
                 )->FT: # Tab container
    "A TabContainer where children will be different tabs"
    base_cls = "-mb-px text-sm font-medium text-center text-gray-500 dark:text-gray-400"
    ul_cls = "flex flex-wrap -mb-px text-sm font-medium text-center text-gray-500 dark:text-gray-400"
    cls = stringify(cls)
    return Div(cls=(FlexT.block,FlexT.wrap,base_cls,"mb-2 border-b-2 border-gray-200 dark:border-gray-700"),**kwargs)(Ul(cls=(ul_cls,stringify(cls)), data_tabs_active_classes=active_items_cls, data_tabs_inactive_classes=inactive_items_cls,**kwargs)(*li))

# %% ../nbs/01_flowbite.ipynb 21
class FormT(VEnum):
    default = "max-w-md mx-auto"
    slim = "max-w-sm mx-auto"


def Form(*c, # contents of Form tag (often Buttons, FormLabels, and LabelInputs)
          cls=FormT.default, # Classes in addition to Form styling (default is 'space-y-3' to prevent scrunched up form elements)
          **kwargs # Additional args for Form tag
          )->FT: # Form(..., cls='space-y-3')
    "A Form with default spacing between form elements"
    return fh.Form(*c, cls=stringify(cls), **kwargs)

class LabelInputT(VEnum):
    default = 'block mb-2 text-sm font-medium text-gray-900 dark:text-white'
    success = 'block mb-2 text-sm font-medium text-green-700 dark:text-green-500'
    error = 'block mb-2 text-sm font-medium text-red-700 dark:text-red-500'

class InputT(VEnum):
    default = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'
    success = 'bg-green-50 border border-green-500 text-green-900 dark:text-green-400 placeholder-green-700 dark:placeholder-green-500 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5 dark:bg-gray-700 dark:border-green-500'
    error = 'bg-red-50 border border-red-500 text-red-900 placeholder-red-700 text-sm rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500 block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500 dark:border-red-500'

def Input(label:str|FT = None, # FormLabel content (often text)
          lbl_cls=LabelInputT.default, # Additional classes for `FormLabel`
          cls=InputT.default, # Additional classes for `Input`
          help_cls=TextT.sm, # Additional classes for `P` (help text)
          div_cls='mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          placeholder='', # Placeholder text for the input
          required=False, # Whether the input is required
          help_text:str|FT = None, # Help text for the input
          icon='', # Icon for the input
          disabled=False, # Whether the input is disabled
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(
                Label(label, fr=id, cls=lbl_cls) if label else None,
                Div(cls="relative")(
                    Div(
                        Icon(icon,cls='w-4 h-4 text-gray-500 dark:text-gray-400'),
                        cls='absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none'
                    ),
                    fh.Input(id=id, placeholder=placeholder, required=required, cls=(cls,'ps-10' if icon else '','cursor-not-allowed' if disabled else ''), disabled=disabled, **kwargs)
                ),
                P(help_text, cls=(help_cls,"mt-2")),
                cls=(div_cls),                
            )

def TextArea(label:str|FT = None, # FormLabel content (often text)
          lbl_cls=LabelInputT.default, # Additional classes for `FormLabel`
          cls=InputT.default, # Additional classes for `Input`
          help_cls=TextT.sm, # Additional classes for `P` (help text)
          div_cls='mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          placeholder='', # Placeholder text for the input
          required=False, # Whether the input is required
          help_text:str|FT = None, # Help text for the input
          icon='', # Icon for the input
          disabled=False, # Whether the input is disabled
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(
                Label(label, fr=id, cls=lbl_cls) if label else None,
                Div(cls="relative")(
                    Div(
                        Icon(icon,cls='w-4 h-4 text-gray-500 dark:text-gray-400'),
                        cls='absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none'
                    ),
                    fh.Textarea(id=id, placeholder=placeholder, required=required, cls=(cls,'ps-10' if icon else '','cursor-not-allowed' if disabled else ''), disabled=disabled, **kwargs)
                ),
                P(help_text, cls=(help_cls,"mt-2")),
                cls=(div_cls),                
            )

def Options(*c,                    # Content for an `Option`
            selected_idx:int=None, # Index location of selected `Option`
            disabled_idxs:set=None # Idex locations of disabled `Options`
           ):
    "Helper function to wrap things into `Option`s for use in `Select`"
    return [fh.Option(o) for i,o in enumerate(c)]

def Select(*options, # Options for the select dropdown (can use `Options` helper function to create)
          label:str|FT = None, # FormLabel content (often text)
          lbl_cls=LabelInputT.default, # Additional classes for `FormLabel`
          cls=InputT.default, # Additional classes for `Input`
          help_cls=TextT.sm, # Additional classes for `P` (help text)
          div_cls='mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          placeholder='', # Placeholder text for the input
          required=False, # Whether the input is required
          help_text:str|FT = None, # Help text for the input
          icon='', # Icon for the input
          disabled=False, # Whether the input is disabled
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(
                Label(label, fr=id, cls=lbl_cls) if label else None,
                Div(cls="relative")(
                    Div(
                        Icon(icon,cls='w-4 h-4 text-gray-500 dark:text-gray-400'),
                        cls='absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none'
                    ),
                    fh.Select(*options,id=id, placeholder=placeholder, required=required, cls=(cls,'ps-10' if icon else '','cursor-not-allowed' if disabled else ''), disabled=disabled, **kwargs)
                ),
                P(help_text, cls=(help_cls,"mt-2")),
                cls=(div_cls),                
            )

class RadioT(VEnum):
    default = "w-4 h-4 text-primary-600 bg-gray-100 border-gray-300 focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
    success = "w-4 h-4 text-green-600 bg-green-100 border-green-300 focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-green-600"
    error = "w-4 h-4 text-red-600 bg-red-100 border-red-300 focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-red-600"

def Radio(label:str|FT = None, # FormLabel content (often text)
          lbl_cls=TextT.medium, # Additional classes for `FormLabel`
          cls=RadioT.default, # Additional classes for `Input`
          help_cls=TextT.xs+TextT.gray, # Additional classes for `P` (help text)
          div_cls='flex mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          help_text:str|FT = None, # Help text for the input
          disabled=False, # Whether the input is disabled
          checked=False, # Whether the input is selected
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(cls=div_cls)(
                Div(cls='flex items-center h-5')(
                    fh.Input(id=id, aria_describedby=f'{id}-text', type='radio', value='', cls=(cls,'cursor-not-allowed' if disabled else ''), disabled=disabled, checked=checked, **kwargs)
                ),
                Div(cls='ms-2 text-sm')(
                    Label(label, fr=id, cls=lbl_cls),
                    P(help_text, id=f'{id}-text', cls=help_cls)
                ),                         
            )

class CheckboxT(VEnum):
    default="w-4 h-4 text-primary-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
    success = "w-4 h-4 text-green-600 bg-green-100 border-green-300 rounded-sm focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-green-600"
    error = "w-4 h-4 text-red-600 bg-red-100 border-red-300 rounded-sm focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-red-600"

def Checkbox(label:str|FT = None, # FormLabel content (often text)
          lbl_cls=TextT.medium, # Additional classes for `FormLabel`
          cls=CheckboxT.default, # Additional classes for `Input`
          help_cls=TextT.xs+TextT.gray, # Additional classes for `P` (help text)
          div_cls='flex mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          help_text:str|FT = None, # Help text for the input
          disabled=False, # Whether the input is disabled
          checked=False, # Whether the input is selected
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(cls=div_cls)(
                Div(cls='flex items-center h-5')(
                    fh.Input(id=id, aria_describedby=f'{id}-text', type='checkbox', value='', cls=(cls,'cursor-not-allowed' if disabled else ''), disabled=disabled, checked=checked, **kwargs)
                ),
                Div(cls='ms-2 text-sm')(
                    Label(label, fr=id, cls=lbl_cls),
                    P(help_text, id=f'{id}-text', cls=help_cls)
                ),                         
            )

class SwitchT(VEnum):
    default = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 dark:peer-focus:ring-primary-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-primary-600 dark:peer-checked:bg-primary-600"
    success = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-green-300 dark:peer-focus:ring-green-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600 dark:peer-checked:bg-green-600"
    error = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-red-300 dark:peer-focus:ring-red-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-red-600 dark:peer-checked:bg-red-600"

def Switch(label:str|FT = None, # FormLabel content (often text)
          lbl_cls=TextT.medium, # Additional classes for `FormLabel`
          cls=SwitchT.default, # Additional classes for `Input`
          div_cls='flex mb-5', # Classes on container (default is `'space-y-2'` to prevent scrunched up form elements)
          id='', # id for `FormLabel` and `Input` (`id`, `name` and `for` attributes are set to this value)
          disabled=False, # Whether the input is disabled
          checked=False, # Whether the input is selected
          **kwargs # Additional args for `Input`
          )->FT:    
    return Div(cls=div_cls)(Label(cls='inline-flex items-center cursor-pointer')(
            fh.Input(type='checkbox',id=id, value='', cls='sr-only peer',disabled=disabled,checked=checked,**kwargs),
            Div(cls=cls,disabled=disabled),
            Span(label, cls=(lbl_cls,"ms-3"))
        )
    )
# Label(cls='inline-flex items-center mb-5 cursor-pointer')(
#             Input(type='checkbox', cls='sr-only peer',disabled=disabled,checked=checked),
#             Div(cls="relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600 dark:peer-checked:bg-blue-600"),
#             Span(label, cls=(lbl_cls,"ms-3"))
#         )



# %% ../nbs/01_flowbite.ipynb 23
def Upload(label:str|FT = None, # Contents of Upload tag button (often text)
          help_text:str|FT = None, # Help text for the input
          cls="mb-5", # Classes in addition to Upload styling
          lbl_cls='block mb-2 text-sm font-medium text-gray-900 dark:text-white', # Classes for the label
          multiple=False, # Whether to allow multiple file selection
          accept=None, # File types to accept (e.g. 'image/*')
          button_cls='block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400', # Classes for the button
          id='file_input', # ID for the file input
          name=None, # Name for the file input
          **kwargs # Additional args for the outer div
          )->FT: # Div(Input(type='file'), Button(...))
    "A file upload component with default styling"
    input_kwargs = {'type': 'file', 'multiple': multiple}
    if accept: input_kwargs['accept'] = accept
    if id: input_kwargs['id'] = id
    if name: input_kwargs['name'] = name
    return Div(cls=cls)(
        Label(label, fr=id, cls=(lbl_cls,'block mb-2')),
        fh.Input(aria_describedby=f'{id}_help', cls=button_cls,**input_kwargs),
        P(help_text, id=f'{id}_help', cls='mt-1 text-sm text-gray-500 dark:text-gray-300')
    )
