"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['stringify', 'str2cls', 'VEnum']

# %% ../nbs/00_core.ipynb 2
from enum import Enum, auto
from fastcore.all import *

# %% ../nbs/00_core.ipynb 4
# need a better name, stringify might be too general for what it does 
def stringify(o # String, Tuple, or Enum options we want stringified
             ): # String that can be passed FT comp args (such as `cls=`)
    "Converts input types into strings that can be passed to FT components"  
    if is_listy(o): return ' '.join(map(str,o)) if o else ""
    return o.__str__()

def str2cls(base: str, txt: str) -> str:
    """Convert base and text into a class name"""
    return f"{base}-{txt.replace('_', '-')}".strip('-')

# %% ../nbs/00_core.ipynb 6
class VEnum(Enum):
    def __str__(self): return self.value
    def __add__(self, other): return stringify((self,other))
    def __radd__(self, other): return stringify((other,self))
