# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_flowbite.ipynb.

# %% auto 0
__all__ = ['Meter']

# %% ../nbs/01_flowbite.ipynb 1
import fasthtml.common as fh
from .core import *
from fasthtml.common import Div, Span, FT
from typing import Union
from fastcore.all import *
from enum import Enum
from .base import *
from .containers import *
from .media import *
from .buttons import *
from typing import Literal

import mistletoe
from lxml import html, etree

# %% ../nbs/01_flowbite.ipynb 2
def Meter(*c:FT|str, # Contents of Meter tag
          value:float=None, # Current value
          min:float=None, # Minimum value
          max:float=None, # Maximum value
          cls:Enum|str|tuple=(), # Additional classes
          **kwargs # Additional args for Meter tag
          )->FT:
    "Styled meter element"
    if value is not None: kwargs['value'] = value
    if min is not None: kwargs['min'] = min
    if max is not None: kwargs['max'] = max
    return fh.Meter(*c, cls=('w-full h-2 rounded', stringify(cls)), **kwargs)
