# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/16_skeleton.ipynb.

# %% auto 0
__all__ = ['PlaceholderT', 'Placeholder']

# %% ../nbs/16_skeleton.ipynb 1
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from .core import *
from .base import *

# %% ../nbs/16_skeleton.ipynb 2
class PlaceholderT(VEnum):
    dashed="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700"
    gray="p-4 flex items-center justify-center rounded-sm bg-gray-50 dark:bg-gray-800"

def Placeholder(*c, # Components to put in the placeholder
                  cls=PlaceholderT.dashed, # Additional classes on the placeholder
                  **kwargs # Additional args for `Div` tag
                  )->FT: # Div(..., cls='uk-placeholder')
    "Creates a placeholder"
    return fh.Div(*c, cls=stringify(cls), **kwargs)
