# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/13_badges.ipynb.

# %% auto 0
__all__ = ['BadgeT', 'Badge', 'IconBadge']

# %% ../../nbs/13_badges.ipynb 1
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from ..core import *
from .base import *
from .base_styles import *
from .containers import *
from .media import *
from enum import Enum

# %% ../../nbs/13_badges.ipynb 2

def Badge(*c, # contents of Badge (often text)
           icon=None, # Opinionated small icon to display in the badge
           cls:Enum|str|tuple=BadgeT.default_pill, # Classes in addition to Label styling
           **kwargs # Additional args for Label tag
           )->FT:
    "Flowbite badges, which look like labels"
    return fh.Span(Icon(icon,cls='w-2.5 h-2.5 me-1.5') if icon else None,*c, cls=(stringify(cls),'inline-flex items-center' if icon else ''), **kwargs)

def IconBadge(icon,
           h="2.5",
           w="2.5",
           cls:Enum|str|tuple=(), # Classes in addition to Badge styling
           icon_cls:Enum|str|tuple=(), # Classes in addition to Icon styling
           **kwargs # Additional args for Badge tag
           )->FT: 
    "Flowbite badges, which look like pills" 
    return fh.Span(Icon(icon,cls=(f'w-{w} h-{h}',stringify(icon_cls))), cls=(stringify(cls),'inline-flex items-center rounded-full p-1'), **kwargs)


