# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_base_styles.ipynb.

# %% auto 0
__all__ = ['Round', 'TextT', 'TextPresets', 'ListT', 'FlexT', 'BackgroundT', 'BtnColor', 'DividerT','FormT', 'LabelInputT', 'InputT',
           'BlockquoteT', 'PT', 'ButtonT', 'ButtonSize', 'ButtonOutline', 'AT', 'HAT', 'ContainerSize', 'SectionT', 'CardT', 'BadgeT', 
           'IconT', 'RadioT', 'CheckboxT', 'SwitchT', 'ModalT', 'NavT', 'NavbarT', 'ProgressT', 'RangeT', 'PlaceholderT', 'SliderItemT',
           'TableT', 'TabContainerT', 'TabItemT', 'Border', 'Shadow','Bg']

from ..core import *
from fastcore.all import *
# TODO: Add animation and effects classes


class Round(VEnum):
    """Button shape variants"""
    default = "rounded-lg"
    full = "rounded-full"
    none = "rounded-none"
    sm = "rounded-sm"
    md = "rounded-md"
    lg = "rounded-lg"
    xl = "rounded-xl"
    _2xl = "rounded-2xl"
    _3xl = "rounded-3xl"
    _4xl = "rounded-4xl"

class Border(VEnum):
    """Border style variants"""
    # Basic borders with light/dark variants
    default = 'border border-gray-300 dark:border-gray-600'
    light = 'border border-gray-200 dark:border-gray-700'
    strong = 'border border-gray-500 dark:border-gray-300'
    
    # Color variants
    primary = 'border border-primary-400 dark:border-primary-600'
    secondary = 'border border-gray-400 dark:border-gray-600'
    success = 'border border-green-400 dark:border-green-600'
    error = 'border border-red-400 dark:border-red-600'
    warning = 'border border-yellow-400 dark:border-yellow-600'
    
    # Special borders
    transparent = 'border border-transparent'
    white = 'border border-white'
    
    # Border sides
    bottom = 'border-b border-gray-200 dark:border-gray-700'
    top = 'border-t border-gray-200 dark:border-gray-700'
    left = 'border-l border-gray-200 dark:border-gray-700'
    right = 'border-r border-gray-200 dark:border-gray-700'
    
    # Hover states
    hover_light = 'border border-gray-200 hover:border-gray-300 dark:border-gray-700 dark:hover:border-gray-700'
    hover_primary = 'border border-primary-400 hover:border-primary-500 dark:border-primary-600 dark:hover:border-primary-500'



class TextT(VEnum):
    """
    Text Styles from Flowbite UI
    """
    # Text Size
    xs, sm, base, lg, xl = 'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl'
    text_2xl, text_3xl, text_4xl = 'text-2xl', 'text-3xl', 'text-4xl'
    text_5xl, text_6xl, text_7xl = 'text-5xl', 'text-6xl', 'text-7xl'
    text_8xl, text_9xl = 'text-8xl', 'text-9xl'
    
    # Text Weight
    thin, extralight, light = 'font-thin', 'font-extralight', 'font-light'
    normal, medium, semibold = 'font-normal', 'font-medium', 'font-semibold'
    bold, extrabold, black = 'font-bold', 'font-extrabold', 'font-black'
    
    # Text Style
    italic = 'italic'
    
    # Text Format
    article='format format-sm sm:format-base lg:format-lg format-primary dark:format-invert'
    # Text Color
    dark = 'text-white dark:text-gray-900'
    gray = 'text-gray-500 dark:text-gray-400'
    muted = 'text-gray-400 dark:text-gray-600'
    primary = 'text-primary-600 dark:text-primary-500'
    # TODO: Add secondary color
    secondary = 'text-purple-600 dark:text-purple-500'
    success = 'text-green-500 dark:text-green-400'
    warning = 'text-yellow-500 dark:text-yellow-400'
    error = 'text-red-600 dark:text-red-500'
    info = 'text-blue-500 dark:text-blue-400'
    
    # Text Alignment
    left, right, center = 'text-left', 'text-right', 'text-center'
    justify, start, end = 'text-justify', 'text-start', 'text-end'
    
    # Vertical Alignment
    top, middle, bottom = 'align-top', 'align-middle', 'align-bottom'
    
    # Text Decoration
    underline, line_through = 'underline', 'line-through'
    uppercase, lowercase = 'uppercase', 'lowercase'
    capitalize, normal_case = 'capitalize', 'normal-case'
    
    # Line Height
    leading_none = 'leading-none'
    leading_tight = 'leading-tight'
    leading_snug = 'leading-snug'
    leading_normal = 'leading-normal'
    leading_relaxed = 'leading-relaxed'
    leading_loose = 'leading-loose'
    
    # Letter Spacing
    tracking_tighter = 'tracking-tighter'
    tracking_tight = 'tracking-tight'
    tracking_normal = 'tracking-normal'
    tracking_wide = 'tracking-wide'
    tracking_wider = 'tracking-wider'
    tracking_widest = 'tracking-widest'
    
    # Text Wrapping
    truncate = 'truncate'
    whitespace_normal = 'whitespace-normal'
    whitespace_nowrap = 'whitespace-nowrap'
    whitespace_pre = 'whitespace-pre'
    whitespace_pre_line = 'whitespace-pre-line'
    whitespace_pre_wrap = 'whitespace-pre-wrap'
    
    # Other
    highlight = 'bg-yellow-200 dark:bg-yellow-400 text-black'
    abbr = 'border-b border-dotted border-gray-300 dark:border-gray-600 hover:cursor-help'
    kbd_default = stringify((Border.default,Round.sm,"font-mono px-1.5 py-0.5 text-sm bg-gray-200 dark:bg-gray-800 shadow-sm"))
    kbd_advanced = stringify((Border.default,Round.lg,"px-2 py-1.5 text-xs font-semibold text-gray-800 bg-gray-100 dark:bg-gray-600 dark:text-gray-100"))
    samp = stringify((Round.sm,"font-mono bg-gray-200 dark:bg-gray-800 px-1"))

class TextPresets(VEnum):
    """
    Common Typography Presets for Flowbite UI
    """
    muted_sm = stringify((TextT.muted, TextT.sm))
    muted_lg = stringify((TextT.muted, TextT.lg))
    
    bold_sm = TextT.bold+TextT.sm
    bold_lg = TextT.bold+TextT.lg
    
    primary_bold = stringify((TextT.primary, TextT.bold))
    success_bold = stringify((TextT.success, TextT.bold))
    warning_bold = stringify((TextT.warning, TextT.bold))
    error_bold = stringify((TextT.error, TextT.bold))
    
    md_weight_sm = stringify((TextT.sm, TextT.medium))
    md_weight_muted = stringify((TextT.medium, TextT.muted))

    """Text heading variants for Flowbite components"""
    h1 = "text-5xl font-extrabold dark:text-white mb-4"
    h2 = "text-4xl font-bold dark:text-white mb-3"
    h3 = "text-3xl font-bold dark:text-white mb-2"
    h4 = "text-2xl font-bold dark:text-white mb-1"
    h5 = "text-xl font-bold dark:text-white mb-0.5"
    h6 = "text-lg font-bold dark:text-white"

class PT(VEnum):
    default = TextT.gray+"my-3"
    lead = TextT.gray+"my-3 text-lg md:text-xl"
    capital_first = "my-3 text-gray-500 dark:text-gray-400 first-line:uppercase first-line:tracking-widest first-letter:text-7xl first-letter:font-bold first-letter:text-gray-900 dark:first-letter:text-gray-100 first-letter:me-3 first-letter:float-start"
    link = "my-3 font-medium text-primary-600 underline dark:text-primary-500 dark:hover:text-primary-600 hover:text-primary-700 hover:no-underline"
    primary = TextT.primary+"my-3"
    secondary = TextT.secondary+"my-3"
    xs = TextT.xs+"my-3"
    sm = TextT.sm+"my-3"

class ListT(VEnum):
    'List styles using Tailwind CSS'
    ul = 'max-w-md space-y-1 list-disc list-inside' 
    ol = 'mt-2 space-y-1 list-decimal list-inside'
    dl = 'divide-y divide-gray-200'
    dt = 'mb-1 text-gray-500 dark:text-gray-400'
    dd = 'mb-1'
    horizontal = 'flex flex-wrap items-center'
    horizontal_center = 'flex flex-wrap items-center justify-center'
    unstyled = 'max-w-md space-y-1 list-none list-inside'
    nested_ol = 'ps-5 mt-2 space-y-1 list-decimal list-inside'
    nested_ul = 'ps-5 mt-2 space-y-1 list-disc list-inside'


class Bg(VEnum):
    """Button style variants for Flowbite components"""
    # Base styles
    primary = "bg-primary-700 dark:bg-primary-600"
    blue = "bg-blue-700 dark:bg-blue-600"
    green = "bg-green-700 dark:bg-green-600"
    cyan = "bg-cyan-700 dark:bg-cyan-600"
    teal = "bg-teal-700 dark:bg-teal-600"
    lime = "bg-lime-700 dark:bg-lime-600"
    red = "bg-red-700 dark:bg-red-600"
    yellow = "bg-yellow-400 dark:bg-yellow-600"
    pink = "bg-pink-700 dark:bg-pink-600"
    purple = "bg-purple-700 dark:bg-purple-600"
    
    primary_hover = "bg-primary-700 hover:bg-primary-800 dark:bg-primary-600 dark:hover:bg-primary-700"
    blue_hover = "bg-blue-700 hover:bg-blue-800 dark:bg-blue-600 dark:hover:bg-blue-700"
    green_hover = "bg-green-700 hover:bg-green-800 dark:bg-green-600 dark:hover:bg-green-700"
    cyan_hover = "bg-cyan-700 hover:bg-cyan-800 dark:bg-cyan-600 dark:hover:bg-cyan-700"
    teal_hover = "bg-teal-700 hover:bg-teal-800 dark:bg-teal-600 dark:hover:bg-teal-700"
    lime_hover = "bg-lime-700 hover:bg-lime-800 dark:bg-lime-600 dark:hover:bg-lime-700"
    red_hover = "bg-red-700 hover:bg-red-800 dark:bg-red-600 dark:hover:bg-red-700"
    yellow_hover = "bg-yellow-400 hover:bg-yellow-500 dark:bg-yellow-600 dark:hover:bg-yellow-500"
    pink_hover = "bg-pink-700 hover:bg-pink-800 dark:bg-pink-600 dark:hover:bg-pink-700"
    purple_hover = "bg-purple-700 hover:bg-purple-800 dark:bg-purple-600 dark:hover:bg-purple-700"
    
    grad_primary = "text-white bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700"
    grad_blue = "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700"
    grad_green = "text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700"
    grad_cyan = "text-white bg-gradient-to-r from-cyan-500 via-cyan-600 to-cyan-700"
    grad_teal = "text-white bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700"
    grad_lime = "text-white bg-gradient-to-r from-lime-500 via-lime-600 to-lime-700"
    grad_red = "text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700"
    grad_yellow = "text-white bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700"
    grad_pink = "text-white bg-gradient-to-r from-pink-500 via-pink-600 to-pink-700"
    grad_purple = "text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700"
    #Duotone
    purple_blue = "text-white bg-gradient-to-br from-purple-600 to-blue-500"
    cyan_blue = "text-white bg-gradient-to-r from-cyan-500 to-blue-500"
    green_blue = "text-white bg-gradient-to-br from-green-400 to-blue-600"
    purple_pink = "text-white bg-gradient-to-r from-purple-500 to-pink-500"
    pink_orange = "text-white bg-gradient-to-br from-pink-500 to-orange-400"
    teal_lime = "text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200"
    red_yellow = "text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200"

    grad_shadow_primary = 'text-white bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 shadow-lg shadow-primary-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_blue = 'text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 shadow-lg shadow-blue-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_green = 'text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 shadow-lg shadow-green-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_cyan = 'text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 shadow-lg shadow-cyan-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_teal = 'text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 shadow-lg shadow-teal-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_lime = 'text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 shadow-lg shadow-lime-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_red = 'text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 shadow-lg shadow-red-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_pink = 'text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 shadow-lg shadow-pink-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_purple = 'text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 shadow-lg shadow-purple-500/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'

class Shadow(VEnum):
    """Shadow styles for Flowbite components"""
    sm = 'shadow-sm'
    md = 'shadow-md'
    lg = 'shadow-lg'
    xl = 'shadow-xl'
    _2xl = 'shadow-2xl'
    _3xl = 'shadow-3xl'
    _4xl = 'shadow-4xl'
    _5xl = 'shadow-5xl'
    _6xl = 'shadow-6xl'
    _7xl = 'shadow-7xl'
    _8xl = 'shadow-8xl'

class BtnColor(VEnum):
    """Button style variants for Flowbite components"""
    # Base styles
    primary = "bg-primary-700 hover:bg-primary-800 dark:bg-primary-600 dark:hover:bg-primary-700  text-white focus:ring-primary-300 dark:focus:ring-primary-800"
    blue = "bg-blue-700 hover:bg-blue-800 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 text-white focus:ring-blue-300"
    green = "bg-green-700 hover:bg-green-800 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 text-white focus:ring-green-300"
    cyan = "bg-cyan-700 hover:bg-cyan-800 dark:bg-cyan-600 dark:hover:bg-cyan-700 dark:focus:ring-cyan-800 text-white focus:ring-cyan-300"
    teal = "bg-teal-700 hover:bg-teal-800 dark:bg-teal-600 dark:hover:bg-teal-700 dark:focus:ring-teal-800 text-white focus:ring-teal-300"
    lime = "bg-lime-700 hover:bg-lime-800 dark:bg-lime-600 dark:hover:bg-lime-700 dark:focus:ring-lime-800 text-white focus:ring-lime-300"
    red = "bg-red-700 hover:bg-red-800 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 text-white focus:ring-red-300"
    yellow = "bg-yellow-400 hover:bg-yellow-500 dark:focus:ring-yellow-900 text-white focus:ring-yellow-300"
    pink = "bg-pink-700 hover:bg-pink-800 dark:bg-pink-600 dark:hover:bg-pink-700 dark:focus:ring-pink-900 text-white focus:ring-pink-300"
    purple = "bg-purple-700 hover:bg-purple-800 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900 text-white focus:ring-purple-300"
    
    grad_primary = "text-white bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-primary-300 dark:focus:ring-primary-800"
    grad_blue = "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
    grad_green = "text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800"
    grad_cyan = "text-white bg-gradient-to-r from-cyan-500 via-cyan-600 to-cyan-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800"
    grad_teal = "text-white bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 dark:focus:ring-teal-800"
    grad_lime = "text-white bg-gradient-to-r from-lime-500 via-lime-600 to-lime-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800"
    grad_red = "text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800"
    grad_yellow = "text-white bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-yellow-300 dark:focus:ring-yellow-800"
    grad_pink = "text-white bg-gradient-to-r from-pink-500 via-pink-600 to-pink-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800"
    grad_purple = "text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800"
    #Duotone
    purple_blue = "text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
    cyan_blue = "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800"
    green_blue = "text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800"
    purple_pink = "text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800"
    pink_orange = "text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
    teal_lime = "text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-teal-700"
    red_yellow = "text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400"

    grad_shadow_primary = 'text-white bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-primary-300 dark:focus:ring-primary-800 shadow-lg shadow-primary-500/50 dark:shadow-lg dark:shadow-primary-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_blue = 'text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_green = 'text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 shadow-lg shadow-green-500/50 dark:shadow-lg dark:shadow-green-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_cyan = 'text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_teal = 'text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 dark:focus:ring-teal-800 shadow-lg shadow-teal-500/50 dark:shadow-lg dark:shadow-teal-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_lime = 'text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_red = 'text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_pink = 'text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 shadow-lg shadow-pink-500/50 dark:shadow-lg dark:shadow-pink-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'
    grad_shadow_purple = 'text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 shadow-lg shadow-purple-500/50 dark:shadow-lg dark:shadow-purple-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2'


class IconT(VEnum):
    default = "w-4 h-4 text-gray-500 dark:text-gray-400"
    muted = "w-4 h-4 text-gray-400 dark:text-gray-600"
    text = "w-4 h-4 text-gray-900 dark:text-white"
    badge = "w-2.5 h-2.5 me-1.5"
    nav = "me-2 shrink-0 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
    primary = "w-4 h-4 text-primary-700 dark:text-primary-500"
    secondary = "w-4 h-4 text-secondary-700 dark:text-secondary-500"
    success = "w-4 h-4 text-green-700 dark:text-green-500"
    warning = "w-4 h-4 text-yellow-700 dark:text-yellow-500"
    error = "w-4 h-4 text-red-700 dark:text-red-500"
    info = "w-4 h-4 text-blue-700 dark:text-blue-500"

class ButtonSize(VEnum):
    """Button size variants"""
    xs = "px-3 py-2 text-xs font-medium"
    sm = "px-3 py-2 text-sm font-medium"
    base = "px-5 py-2.5 text-sm font-medium"
    lg = "px-5 py-3 text-base font-medium"
    xl = "px-6 py-3.5 text-base font-medium"
    
class ButtonOutline(VEnum):
    """Button outline variants"""
    default = "border border-primary-700 hover:bg-primary-800 dark:border-primary-500 dark:hover:bg-primary-500 text-primary-700 hover:text-white dark:text-primary-500 dark:hover:text-white focus:ring-primary-300 dark:focus:ring-primary-800"
    dark = "border border-gray-800 hover:bg-gray-900 dark:border-gray-600 dark:hover:bg-gray-600 text-gray-900 hover:text-white dark:text-gray-400 dark:hover:text-white focus:ring-gray-300 dark:focus:ring-gray-800"
    green = "border border-green-700 hover:bg-green-800 dark:border-green-500 dark:hover:bg-green-600 text-green-700 hover:text-white dark:text-green-500 dark:hover:text-white focus:ring-green-300 dark:focus:ring-green-800"
    red = "border border-red-700 hover:bg-red-800 dark:border-red-500 dark:hover:bg-red-600 text-red-700 hover:text-white dark:text-red-500 dark:hover:text-white focus:ring-red-300 dark:focus:ring-red-900"
    yellow = "border border-yellow-400 hover:bg-yellow-500 dark:border-yellow-300 dark:hover:bg-yellow-400 text-yellow-400 hover:text-white dark:text-yellow-300 dark:hover:text-white focus:ring-yellow-300 dark:focus:ring-yellow-900"
    purple = "border border-purple-700 hover:bg-purple-800 dark:border-purple-400 dark:hover:bg-purple-500 text-purple-700 hover:text-white dark:text-purple-400 dark:hover:text-white focus:ring-purple-300 dark:focus:ring-purple-900"

class ButtonT(VEnum):
    """Button type variants"""
    primary = BtnColor.primary.value
    secondary = stringify(("bg-white hover:bg-gray-100 dark:bg-gray-800 dark:text-white dark:hover:bg-gray-700 text-gray-900 focus:ring-gray-200 dark:focus:ring-gray-700", Border.default))
    ghost = "hover:bg-gray-100 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-gray-300 dark:focus:ring-gray-700 cursor-pointer"
    link = "dark:text-white cursor-pointer"
    success = BtnColor.green.value   
    warning = BtnColor.yellow.value
    error = BtnColor.red.value
    info = BtnColor.blue.value

class AT(VEnum):
    default = "underline"
    primary = "text-primary-600 dark:text-primary-500 hover:underline"
    muted = "text-gray-500 dark:text-gray-400 hover:underline"
    text = "text-gray-900 dark:text-white hover:underline"
    classic = 'text-blue-600 hover:text-blue-800 underline'
    nav = "flex items-center p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 group"
    
class HAT(VEnum):
    """Anchor tag variants"""
    primary = "ml-2 text-primary-700 opacity-0 transition-opacity dark:text-primary-500 group-hover:opacity-100"
    secondary = "ml-2 text-secondary-700 opacity-0 transition-opacity dark:text-secondary-500 group-hover:opacity-100"

class FlexT(VEnum):
    'Flexbox modifiers using Tailwind CSS'
    def _generate_next_value_(name, start, count, last_values): return name
    
    # Display
    block = 'flex'
    inline = 'inline-flex'
    
    # Horizontal Alignment
    left = 'justify-start' 
    center = 'justify-center'
    right = 'justify-end'
    between = 'justify-between'
    around = 'justify-around'
    
    # Vertical Alignment
    stretch = 'items-stretch'
    top = 'items-start'
    middle = 'items-center' 
    bottom = 'items-end'
    
    # Direction
    row = 'flex-row'
    row_reverse = 'flex-row-reverse'
    column = 'flex-col'
    column_reverse = 'flex-col-reverse'
    
    # Wrap
    nowrap = 'flex-nowrap'
    wrap = 'flex-wrap'
    wrap_reverse = 'flex-wrap-reverse'

class BackgroundT(VEnum):
    primary = "bg-primary-100 dark:bg-primary-800"
    secondary = "bg-gray-100 dark:bg-gray-800"
    success = "bg-green-100 dark:bg-green-800"
    warning = "bg-yellow-100 dark:bg-yellow-800"
    error = "bg-red-100 dark:bg-red-800"
    info = "bg-blue-100 dark:bg-blue-800"

    hover_primary = "bg-primary-100 dark:bg-primary-800 hover:bg-primary-200 dark:hover:bg-primary-700"
    hover_secondary = "bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700"
    hover_success = "bg-green-100 dark:bg-green-800 hover:bg-green-200 dark:hover:bg-green-700"
    hover_warning = "bg-yellow-100 dark:bg-yellow-800 hover:bg-yellow-200 dark:hover:bg-yellow-700"
    hover_error = "bg-red-100 dark:bg-red-800 hover:bg-red-200 dark:hover:bg-red-700"
    hover_info = "bg-blue-100 dark:bg-blue-800 hover:bg-blue-200 dark:hover:bg-blue-700"
    
    grad_primary = "bg-gradient-to-r from-primary-500 via-primary-600 to-primary-700 hover:bg-gradient-to-br"
    grad_secondary = "bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br"
    grad_success = "bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br"
    grad_warning = "bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br"
    grad_error = "bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br"
    grad_info = "bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br"
    grad_blue = "bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br"
    grad_green = "bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br"
    grad_cyan = "bg-gradient-to-r from-cyan-500 via-cyan-600 to-cyan-700 hover:bg-gradient-to-br"
    grad_teal = "bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700 hover:bg-gradient-to-br"
    grad_lime = "bg-gradient-to-r from-lime-500 via-lime-600 to-lime-700 hover:bg-gradient-to-br"
    grad_red = "bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br"
    grad_yellow = "bg-gradient-to-r from-yellow-500 via-yellow-600 to-yellow-700 hover:bg-gradient-to-br"
    grad_pink = "bg-gradient-to-r from-pink-500 via-pink-600 to-pink-700 hover:bg-gradient-to-br"
    grad_purple = "bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br"
    #Duotone
    purple_blue = "bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl"
    cyan_blue = "bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl"
    green_blue = "bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl"
    purple_pink = "bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l"
    pink_orange = "bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl"
    teal_lime = "bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200"
    red_yellow = "bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl"

class ContainerSize(VEnum):
    """Container size variants for Flowbite components"""
    # Base container with responsive padding
    default = "container mx-auto"    
    # Fixed width containers based on Flowbite size variables
    # These add mx-auto to center and have responsive padding
    _3xs = "max-w-3xs" # --container-3xs:16rem
    _2xs = "max-w-2xs" # --container-2xs:18rem
    xs = "max-w-xs"  # --container-xs:20rem
    sm = "max-w-sm"  # --container-sm:24rem
    md = "max-w-md"  # --container-md:28rem
    lg = "max-w-lg"  # --container-lg:32rem
    xl = "max-w-xl"  # --container-xl:36rem
    _2xl = "max-w-2xl" # --container-2xl:42rem
    _3xl = "max-w-3xl" # --container-3xl:48rem
    _4xl = "max-w-4xl" # --container-4xl:56rem
    _5xl = "max-w-5xl" # --container-5xl:64rem
    _6xl = "max-w-6xl" # --container-6xl:72rem
    _7xl = "max-w-7xl" # --container-7xl:80rem
    # Special container types
    fluid = "w-full px-4"  # Full width with padding
    responsive = "w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl 2xl:max-w-2xl px-4"  # Responsive sizing

class SectionT(VEnum):
    default = "py-12 px-4"
    muted = BackgroundT.secondary+"py-12 px-4"
    primary = BackgroundT.primary+"py-12 px-4"
    secondary = BackgroundT.secondary+"py-12 px-4"
    xs = ContainerSize.xs+"py-12 px-4"
    sm = ContainerSize.sm+"py-12 px-4"
    lg = ContainerSize.lg+"py-12 px-4"
    xl = ContainerSize.xl+"py-12 px-4"

class CardT(VEnum):
    default = stringify((Border.light, 'block max-w-sm p-6 bg-white rounded-lg shadow-sm hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-700'))
    primary = stringify((Border.light, 'block max-w-sm p-6 bg-primary-50 rounded-lg shadow-sm hover:bg-primary-100 dark:bg-primary-800 dark:hover:bg-primary-700'))
    secondary = 'block max-w-sm p-6 bg-gray-100 border border-gray-200 rounded-lg shadow-sm hover:bg-white dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700'
    destructive = 'block max-w-sm p-6 bg-red-50 border border-gray-200 rounded-lg shadow-sm hover:bg-red-300 dark:bg-red-800 dark:border-gray-700 dark:hover:bg-red-700'
    horizontal = 'flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow-sm md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700'
    hover = 'hover:shadow-lg hover:-translate-y-1 transition-all duration-200'
    plain = 'block max-w-sm p-6 border border-gray-200 rounded-lg shadow-sm dark:border-gray-700'
    # Card elements
    title = 'mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white'
    body = 'font-normal text-gray-700 dark:text-gray-400'
    footer = 'mt-4'

class BadgeT(VEnum):
    default = 'bg-primary-100 text-primary-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-primary-900 dark:text-primary-300'
    dark = 'bg-gray-100 text-gray-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-gray-300'
    red = 'bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-red-900 dark:text-red-300'
    green = 'bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-green-900 dark:text-green-300'
    blue = 'bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-blue-900 dark:text-blue-300'
    yellow = 'bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-yellow-900 dark:text-yellow-300'
    indigo = 'bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-indigo-900 dark:text-indigo-300'
    purple = 'bg-purple-100 text-purple-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-purple-900 dark:text-purple-300'
    pink = 'bg-pink-100 text-pink-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-pink-900 dark:text-pink-300'

    default_lg ='bg-primary-100 text-primary-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-primary-900 dark:text-primary-300'
    dark_lg ='bg-gray-100 text-gray-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-gray-300'
    red_lg ='bg-red-100 text-red-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-red-900 dark:text-red-300'
    green_lg ='bg-green-100 text-green-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-green-900 dark:text-green-300'
    blue_lg ='bg-blue-100 text-blue-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-blue-900 dark:text-blue-300'
    yellow_lg ='bg-yellow-100 text-yellow-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-yellow-900 dark:text-yellow-300'
    indigo_lg ='bg-indigo-100 text-indigo-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-indigo-900 dark:text-indigo-300'
    purple_lg ='bg-purple-100 text-purple-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-purple-900 dark:text-purple-300'
    pink_lg ='bg-pink-100 text-pink-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-pink-900 dark:text-pink-300'

    default_outline='bg-primary-100 text-primary-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-primary-400 border border-primary-400'
    dark_outline='bg-gray-100 text-gray-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-gray-400 border border-gray-500'
    red_outline='bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-red-400 border border-red-400'
    green_outline='bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-green-400 border border-green-400'
    blue_outline='bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-blue-400 border border-blue-400'
    yellow_outline='bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-yellow-400 border border-yellow-400'
    indigo_outline='bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-indigo-400 border border-indigo-400'
    purple_outline='bg-purple-100 text-purple-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-purple-400 border border-purple-400'
    pink_outline='bg-pink-100 text-pink-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-gray-700 dark:text-pink-400 border border-pink-400'

    default_pill='bg-primary-100 text-primary-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-primary-900 dark:text-primary-300'
    dark_pill='bg-gray-100 text-gray-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-gray-700 dark:text-gray-300'
    red_pill='bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300'
    green_pill='bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300'
    blue_pill='bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300'
    yellow_pill='bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300'
    indigo_pill='bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-indigo-900 dark:text-indigo-300'
    purple_pill='bg-purple-100 text-purple-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-purple-900 dark:text-purple-300'
    pink_pill='bg-pink-100 text-pink-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-pink-900 dark:text-pink-300'

class BlockquoteT(VEnum):
    """Blockquote variants"""
    default = "italic font-semibold text-gray-900 dark:text-white p-4 my-4"
    solid = "italic font-semibold text-gray-900 dark:text-white p-4 my-4 border-s-4 border-gray-300 bg-gray-50 dark:border-gray-600 dark:bg-gray-800"
    secondary = "border-l-4 border-gray-300 dark:border-gray-600"
    success = "border-l-4 border-green-500"
    default_no_spacing = "italic font-semibold text-gray-900 dark:text-white"

class DividerT(VEnum):
    default = "h-px my-8 bg-gray-200 border-0 dark:bg-gray-600"
    vertical = "h-full w-px mx-4 bg-gray-200 border-0 dark:bg-gray-600"
    trimmed = "w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded-sm md:my-10 dark:bg-gray-600"
    vertical_strong = 'w-64 h-1 my-8 bg-gray-200 border-0 rounded-sm dark:bg-gray-700'
    trimmed_vertical = "h-48 w-1 my-auto mx-4 bg-gray-100 border-0 rounded-sm md:mx-10 dark:bg-gray-600"
    nav = "border-t border-gray-200 dark:border-gray-700"
# Forms

class FormT(VEnum):
    default = "max-w-md mx-auto"
    slim = "max-w-sm mx-auto"


class LabelInputT(VEnum):
    default = 'block mb-2 text-sm font-medium text-gray-900 dark:text-white'
    success = 'block mb-2 text-sm font-medium text-green-700 dark:text-green-500'
    error = 'block mb-2 text-sm font-medium text-red-700 dark:text-red-500'


class InputT(VEnum):
    default = stringify((Border.default, 'bg-gray-50 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'))
    success = stringify((Border.success, 'bg-green-50 text-green-900 dark:text-green-400 placeholder-green-700 dark:placeholder-green-500 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5 dark:bg-gray-700'))
    error = stringify((Border.error, 'bg-red-50 text-red-900 placeholder-red-700 text-sm rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500 block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500'))

class RadioT(VEnum):
    default = stringify((Border.default, "w-4 h-4 text-primary-600 bg-gray-100 focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"))
    success = stringify((Border.success, "w-4 h-4 text-green-600 bg-green-100 focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-green-600"))
    error = stringify((Border.error, "w-4 h-4 text-red-600 bg-red-100 focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-red-600"))

class CheckboxT(VEnum):
    default= stringify((Border.default, "w-4 h-4 text-primary-600 bg-gray-100 rounded-sm focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700"))
    success = stringify((Border.success, "w-4 h-4 text-green-600 bg-green-100 rounded-sm focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700"))
    error = stringify((Border.error, "w-4 h-4 text-red-600 bg-red-100 rounded-sm focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700"))

class SwitchT(VEnum):
    default = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 dark:peer-focus:ring-primary-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-primary-600 dark:peer-checked:bg-primary-600"
    success = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-green-300 dark:peer-focus:ring-green-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600 dark:peer-checked:bg-green-600"
    error = "relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-red-300 dark:peer-focus:ring-red-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:w-5 after:h-5 after:transition-all dark:border-gray-600 peer-checked:bg-red-600 dark:peer-checked:bg-red-600"

# Modals
class ModalT(VEnum):
    """Modal styling variants for Flowbite components"""
    # Container styles
    container = 'hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full'
    
    # Dialog styles
    dialog = 'relative p-4 w-full max-h-full'
    dialog_inner = 'relative bg-white rounded-lg shadow-sm dark:bg-gray-700'
    
    # Header styles
    header = 'flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600 border-gray-200'
    
    # Body styles
    body = 'p-4 md:p-5'
    
    # Footer styles
    footer = 'flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600'
    
    # Title styles
    title = 'text-lg font-semibold text-gray-900 dark:text-white'
    
    # Close button styles
    close_btn = 'text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm h-8 w-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white'
    
    # Size variants for dialog
    sm = 'sm:max-w-sm'  # Small modal
    md = 'max-w-md'     # Default/medium modal
    lg = 'max-w-lg'     # Large modal
    xl = 'max-w-xl'     # Extra large modal
    _2xl = 'max-w-2xl'  # 2X large modal
    _3xl = 'max-w-3xl'  # 3X large modal
    _4xl = 'max-w-4xl'  # 4X large modal
    _5xl = 'max-w-5xl'  # 5X large modal
    _6xl = 'max-w-6xl'  # 6X large modal
    _7xl = 'max-w-7xl'  # 7X large modal
    
    # Special size variants
    fluid = 'w-full'    # Full width modal
    responsive = 'w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl 2xl:max-w-2xl'  # Responsive modal
    
    # Placement variants
    center = 'items-center justify-center'  # Center modal (default)
    top_left = 'items-start justify-start'  # Top left
    top_center = 'items-start justify-center'  # Top center
    top_right = 'items-start justify-end'  # Top right
    center_left = 'items-center justify-start'  # Center left
    center_right = 'items-center justify-end'  # Center right
    bottom_left = 'items-end justify-start'  # Bottom left
    bottom_center = 'items-end justify-center'  # Bottom center
    bottom_right = 'items-end justify-end'  # Bottom right

class NavT(VEnum):
    default = 'bg-white border-gray-200 dark:bg-gray-800 dark:border-gray-700'
    primary = 'border border-primary-400 dark:border-primary-600 rounded-lg text-primary-500 dark:text-primary-500'
    secondary = 'border border-gray-400 dark:border-gray-600 rounded-lg'
    transparent = 'bg-transparent'
    child_list = 'hidden space-y-2'
    parent_li = 'flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700'
    child_li = 'flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 pl-9'

class NavbarT(VEnum):
    default = 'bg-white border-gray-200 dark:bg-gray-800 dark:border-gray-700'
    dark = 'bg-gray-800 dark:bg-gray-800'
    light = 'bg-white dark:bg-gray-800'
    transparent = 'bg-transparent'

# Progress
class ProgressT(VEnum):
    progress_primary = 'rounded-full bg-primary-600'
    progress_dark = 'rounded-full bg-gray-700 dark:bg-gray-300'
    progress_blue = 'rounded-full bg-blue-600'
    progress_red = 'rounded-full bg-red-600'
    progress_green = 'rounded-full bg-green-600'
    progress_yellow = 'rounded-full bg-yellow-600'
    progress_purple = 'rounded-full bg-purple-600'
    progress_pink = 'rounded-full bg-pink-600'

    bg_default = 'w-full rounded-full bg-gray-200 dark:bg-gray-700'
    bg_primary = 'w-full rounded-full bg-primary-600'
    bg_dark = 'w-full rounded-full bg-gray-300 dark:bg-gray-700'
    bg_blue = 'w-full rounded-full bg-blue-600'
    bg_red = 'w-full rounded-full bg-red-600'
    bg_green = 'w-full rounded-full bg-green-600'
    bg_yellow = 'w-full rounded-full bg-yellow-600'

class RangeT(VEnum):
    default = 'w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700'
    sm = 'w-full h-1 mb-6 bg-gray-200 rounded-lg appearance-none cursor-pointer range-sm dark:bg-gray-700'
    lg = 'w-full h-3 bg-gray-200 rounded-lg appearance-none cursor-pointer range-lg dark:bg-gray-700'

class PlaceholderT(VEnum):
    dashed="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700"
    gray="p-4 flex items-center justify-center rounded-sm bg-gray-50 dark:bg-gray-800"

class SliderItemT(VEnum):
    default = 'absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2'
    linear = 'absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 duration-700 ease-linear'
    ease_out_in = 'absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 duration-700 ease-out-in'
    cubic_bezier = 'absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 duration-700 ease-out-in-cubic'


class TableT(VEnum):
    """Table styling variants for Flowbite components"""
    # Table level styles
    table_default = "w-full text-sm text-left rtl:text-right"
    
    # Container level styles
    container_default = "relative overflow-x-auto"
    container_responsive = "overflow-x-auto"
    container_shadow = "shadow-md"
    
    # Row level styles
    row_default = "bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200"
    row_striped = "odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 border-gray-200"
    row_hover = "hover:bg-gray-50 dark:hover:bg-gray-600"
    row_bordered = "border-b dark:border-gray-700 border-gray-200"
    row_header = "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    row_footer = "font-semibold text-gray-900 dark:text-white"

    # Cell level styles
    cell_default = "px-6 py-4 text-gray-500 dark:text-gray-400"
    cell_expand = "w-full"
    cell_shrink = "w-1"
    cell_first = "font-medium text-gray-900 whitespace-nowrap dark:text-white"
    cell_header = "px-6 py-3"
    cell_footer = "px-6 py-4"

class TabContainerT(VEnum):
    base = stringify((TextT.sm, TextT.medium, 'text-center text-gray-500 dark:text-gray-400', Border.bottom))
    rounded = stringify((Border.default, 'rounded-t-lg bg-gray-50 dark:bg-gray-700 border-b-2 border-gray-50 dark:border-gray-600'))
    plain = stringify((TextT.sm, TextT.medium, 'text-center text-gray-500 dark:text-gray-400'))
    
# TODO: Add horizontal tabs
class TabItemT(VEnum):
    "Enum for the tab item"
    default_active = "text-primary-600 hover:text-primary-600 dark:text-primary-500 dark:hover:text-primary-500 border-primary-600 dark:border-primary-500"
    default_inactive = "dark:border-transparent text-gray-500 hover:text-gray-600 dark:text-gray-400 border-gray-100 hover:border-gray-300 dark:border-gray-700 dark:hover:text-gray-300"
#     pill_active = "py-3 text-white bg-primary-600 rounded-lg active"
#     pill_inactive = "py-3 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white"

