# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_base.ipynb.

# %% auto 0
__all__ = ['HA', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Subtitle', 'Q', 'Em', 'Strong', 'I', 'Small', 'Mark', 'Del', 'Ins', 'Sub',
           'Sup', 'Caption', 'Cite', 'Time', 'Address', 'Abbr', 'Dfn', 'Kbd', 'Samp', 'Var', 'Figure',
           'Summary', 'Details', 'Data', 'S', 'U', 'Output', 'CodeSpan', 'Code', 'CodeBlock', 'P', 'Meter']

# %% ../../nbs/02_base.ipynb 1
import fasthtml.common as fh
from ..core import *
from .base_styles import *
from fasthtml.common import Span, FT
from fastcore.all import *
from enum import Enum

# %% ../../nbs/02_base.ipynb 3
def HA(id:str=None, txt:str='#',cls:Enum|str|tuple=HAT.primary)->FT:
    "A link to an anchor"
    return (fh.Span(id=id, cls='absolute -top-[140px]'),fh.A(txt, href=f'#{id}', aria_label='Link to this section', cls=stringify(cls)))

def H1(*c:FT|str, # Contents of H1 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H1 styling
       id:str=None, # ID of H1 tag
       link:bool=False, # Whether to link the H1 tag
       bold:bool=False, # Whether to bold the H1 tag
       **kwargs # Additional args for H1 tag
       )->FT: # H1(..., cls='uk-h1')
    "H1 with styling and appropriate size"
    if bold:
        cls = (TextT.extrabold, *cls)
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H1(*c,link_el, cls=(TextPresets.h1, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H1(*c, cls=(TextPresets.h1, stringify(cls)), **kwargs)

def H2(*c:FT|str, # Contents of H2 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H2 styling
       id:str=None, # ID of H2 tag  
       link:bool=False, # Whether to link the H2 tag
       bold:bool=False, # Whether to bold the H2 tag
       **kwargs # Additional args for H2 tag
       )->FT: # H2(..., cls='uk-h2')
    "H2 with styling and appropriate size"
    if bold:
        cls = (TextT.bold, *cls)
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H2(*c,link_el, cls=(TextPresets.h2, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H2(*c, cls=(TextPresets.h2, stringify(cls)), **kwargs)

def H3(*c:FT|str, # Contents of H3 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H3 styling   
       id:str=None, # ID of H3 tag  
       link:bool=False, # Whether to link the H3 tag
       **kwargs # Additional args for H3 tag
       )->FT: # H3(..., cls='uk-h3')
    "H3 with styling and appropriate size"
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H3(*c,link_el, cls=(TextPresets.h3, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H3(*c, cls=(TextPresets.h3, stringify(cls)), **kwargs)

def H4(*c:FT|str, # Contents of H4 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H4 styling
       id:str=None, # ID of H4 tag  
       link:bool=False, # Whether to link the H4 tag
       **kwargs # Additional args for H4 tag
       )->FT: # H4(..., cls='uk-h4')
    "H4 with styling and appropriate size"
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H4(*c,link_el, cls=(TextPresets.h4, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H4(*c, cls=(TextPresets.h4, stringify(cls)), **kwargs)

def H5(*c:FT|str, # Contents of H5 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H5 styling
       id:str=None, # ID of H5 tag      
       link:bool=False, # Whether to link the H5 tag
       **kwargs # Additional args for H5 tag
       )->FT: # H5(..., cls='uk-h5')
    "H5 with styling and appropriate size"
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H5(*c,link_el, cls=(TextPresets.h5, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H5(*c, cls=(TextPresets.h5, stringify(cls)), **kwargs)

def H6(*c:FT|str, # Contents of H6 tag (often text)
       cls:Enum|str|tuple=(), # Classes in addition to H6 styling
       id:str=None, # ID of H6 tag      
       link:bool=False, # Whether to link the H6 tag
       **kwargs # Additional args for H6 tag
       )->FT: # H6(..., cls='uk-h6')
    "H6 with styling and appropriate size"
    if link:
        if not id: id = fh.unqid()
        link_el = HA(id)
        return fh.H6(*c,link_el, cls=(TextPresets.h6, stringify(cls), 'relative group'), **kwargs)
    else:        
        return fh.H6(*c, cls=(TextPresets.h6, stringify(cls)), **kwargs)


def Subtitle(*c:FT|str, # Contents of P tag (often text)
         cls:Enum|str|tuple='mt-1.5', # Additional classes
         **kwargs # Additional args for P tag
         )->FT:
    "Styled muted_sm text designed to go under Headings and Titles"
    return fh.P(*c, cls=(TextPresets.muted_sm, stringify(cls)), **kwargs)


def Q(*c:FT|str, # Contents of Q tag (quote)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for Q tag
      )->FT:
    "Styled quotation mark"
    return fh.Q(*c, cls=(TextT.italic,TextT.lg, stringify(cls)), **kwargs)

def Em(*c:FT|str, # Contents of Em tag (emphasis)
       cls:Enum|str|tuple=(), # Additional classes 
       **kwargs # Additional args for Em tag
       )->FT:
    "Styled emphasis text"
    return fh.Em(*c, cls=(TextT.medium, stringify(cls)), **kwargs)

def Strong(*c:FT|str, # Contents of Strong tag
          cls:Enum|str|tuple=(), # Additional classes
          **kwargs # Additional args for Strong tag
          )->FT:
    "Styled strong text" 
    return fh.Strong(*c, cls=(TextT.bold, stringify(cls)), **kwargs)

def I(*c:FT|str, # Contents of I tag (italics)
      cls:Enum|str|tuple=(), # Additional classes
      **kwargs # Additional args for I tag
      )->FT:
    "Styled italic text"
    return fh.I(*c, cls=(TextT.italic, stringify(cls)), **kwargs)

def Small(*c:FT|str, # Contents of Small tag
         cls:Enum|str|tuple=(), # Additional classes
         **kwargs # Additional args for Small tag
         )->FT:
    "Styled small text"
    return fh.Small(*c, cls=(TextT.sm, stringify(cls)), **kwargs)

def Mark(*c:FT|str, # Contents of Mark tag (highlighted text)
        cls:Enum|str|tuple=(), # Additional classes
        **kwargs # Additional args for Mark tag
        )->FT:
    "Styled highlighted text"
    return fh.Mark(*c, cls=(TextT.highlight, stringify(cls)), **kwargs)


def Del(*c:FT|str, # Contents of Del tag (deleted text)
       cls:Enum|str|tuple=(), # Additional classes
       **kwargs # Additional args for Del tag
       )->FT:
    "Styled deleted text"
    return fh.Del(*c, cls=('line-through', TextT.gray, stringify(cls)), **kwargs)

def Ins(*c:FT|str, # Contents of Ins tag (inserted text)
        cls:Enum|str|tuple=(TextT.success, TextT.underline, TextT.sm), # Additional classes
        **kwargs # Additional args for Ins tag
        )->FT:
    "Styled inserted text"
    return fh.Ins(*c, cls=stringify(cls), **kwargs)

def Sub(*c:FT|str, # Contents of Sub tag (subscript)
       cls:Enum|str|tuple=(TextT.sm,' -bottom-1 relative'), # Additional classes
       **kwargs # Additional args for Sub tag
       )->FT:
    "Styled subscript text"
    return fh.Sub(*c, cls=stringify(cls), **kwargs)

def Sup(*c:FT|str, # Contents of Sup tag (superscript) 
        cls:Enum|str|tuple=(TextT.sm,' -top-1 relative'), # Additional classes
        **kwargs # Additional args for Sup tag
        )->FT:
    "Styled superscript text"
    return fh.Sup(*c, cls=stringify(cls), **kwargs)


def Caption(*c:FT|str, cls:Enum|str|tuple=(), **kwargs)->FT:
    "Styled caption text"
    return fh.Caption(
        Span(*c, cls=(TextT.gray, TextT.sm, stringify(cls))),
        **kwargs)


def Cite(*c:FT|str, # Contents of Cite tag
         cls:Enum|str|tuple=(TextT.italic, TextT.gray), # Additional classes
         **kwargs # Additional args for Cite tag
         )->FT:
    "Styled citation text"
    return fh.Cite(*c, cls=stringify(cls), **kwargs)

def Time(*c:FT|str, # Contents of Time tag
         cls:Enum|str|tuple=TextT.gray, # Additional classes
         datetime:str=None, # datetime attribute
         **kwargs # Additional args for Time tag
         )->FT:
    "Styled time element"
    if datetime: kwargs['datetime'] = datetime
    return fh.Time(*c, cls=stringify(cls), **kwargs)

def Address(*c:FT|str, # Contents of Address tag
           cls:Enum|str|tuple=TextT.italic, # Additional classes
           **kwargs # Additional args for Address tag
           )->FT:
    "Styled address element"
    return fh.Address(*c, cls=stringify(cls), **kwargs)


def Abbr(*c:FT|str, # Contents of Abbr tag
         cls:Enum|str|tuple=TextT.abbr, # Additional classes
         title:str=None, # Title attribute for abbreviation
         **kwargs # Additional args for Abbr tag
         )->FT:
    "Styled abbreviation with dotted underline"
    if title: kwargs['title'] = title
    return fh.Abbr(*c, cls=stringify(cls), **kwargs)

def Dfn(*c:FT|str, # Contents of Dfn tag (definition)
        cls:Enum|str|tuple=(TextT.medium, TextT.italic, TextT.gray), # Additional classes
        **kwargs # Additional args for Dfn tag
        )->FT:
    "Styled definition term with italic and medium weight"
    return fh.Dfn(*c, cls=stringify(cls), **kwargs)

def Kbd(*c:FT|str, # Contents of Kbd tag (keyboard input)
        cls:Enum|str|tuple=TextT.kbd_default, # Additional classes
        **kwargs # Additional args for Kbd tag
        )->FT:
    "Styled keyboard input with subtle background"
    return fh.Kbd(*c, cls=stringify(cls), **kwargs)


def Samp(*c:FT|str, # Contents of Samp tag (sample output)
         cls:Enum|str|tuple=(TextT.gray, TextT.samp), # Additional classes
         **kwargs # Additional args for Samp tag
         )->FT:
    "Styled sample output with subtle background"
    return fh.Samp(*c, cls=stringify(cls), **kwargs)

def Var(*c:FT|str, # Contents of Var tag (variable)
        cls:Enum|str|tuple=(TextT.gray, TextT.italic, 'font-mono'), # Additional classes
        **kwargs # Additional args for Var tag
        )->FT:
    "Styled variable with italic monospace"
    return fh.Var(*c, cls=stringify(cls), **kwargs)


def Figure(*c:FT|str, # Contents of Figure tag
          cls:Enum|str|tuple=(), # Additional classes 
          base_cls:Enum|str|tuple='p-4 my-4 border border-gray-200 dark:border-gray-800 rounded-lg shadow-sm bg-gray-200 dark:bg-gray-800', # Additional classes
          **kwargs # Additional args for Figure tag
          )->FT:
    "Styled figure container with card-like appearance"
    return fh.Figure(*c, cls=(stringify(base_cls), stringify(cls)), **kwargs)

def Summary(*c:FT|str, # Contents of Summary tag
           cls:Enum|str|tuple=(), # Additional classes
           base_cls:Enum|str|tuple=(TextT.medium, 'p-3 hover:bg-gray-200 dark:hover:bg-gray-800 cursor-pointer'), # Additional classes
           **kwargs # Additional args for Summary tag
           )->FT:
    "Styled summary element"
    return fh.Summary(*c, cls=(stringify(base_cls), stringify(cls)), **kwargs)


def Details(*c:FT|str, # Contents of Details tag
           cls:Enum|str|tuple=(), # Additional classes
           summary:FT|str=None, # Summary text
           summary_cls:Enum|str|tuple='p-3 hover:bg-gray-200 dark:hover:bg-gray-800 cursor-pointer', # Additional classes
           base_cls:Enum|str|tuple='border border-gray-200 dark:border-gray-800 rounded-lg pl-2', # Additional classes
           **kwargs # Additional args for Details tag
           )->FT:
    "Styled details element"
    # TODO: Add secondary color variant
    return fh.Details(Summary(summary, cls=stringify(summary_cls)), fh.Div(*c, cls="pl-3"), cls=(stringify(base_cls), stringify(cls)), **kwargs)


def Data(*c:FT|str, # Contents of Data tag
         value:str=None, # Value attribute
         cls:Enum|str|tuple=(), # Additional classes
         base_cls:Enum|str|tuple='font-mono text-sm bg-gray-200 dark:bg-gray-800 px-1 rounded', # Additional classes
         **kwargs # Additional args for Data tag
         )->FT:
    "Styled data element"
    if value: kwargs['value'] = value
    return fh.Data(*c, cls=(stringify(base_cls), stringify(cls)), **kwargs)


def S(*c:FT|str, # Contents of S tag (strikethrough)
      cls:Enum|str|tuple=('line-through', TextT.gray), # Additional classes
      **kwargs # Additional args for S tag
      )->FT:
    "Styled strikethrough text (different semantic meaning from Del)"
    return fh.S(*c, cls=stringify(cls), **kwargs)

def U(*c:FT|str, # Contents of U tag (unarticulated annotation)
      cls:Enum|str|tuple=(TextT.underline), # Additional classes
      **kwargs # Additional args for U tag
      )->FT:
    "Styled underline (for proper names in Chinese, proper spelling etc)"
    return fh.U(*c, cls=stringify(cls), **kwargs)

def Output(*c:FT|str, # Contents of Output tag
          form:str=None, # ID of form this output belongs to
          for_:str=None, # IDs of elements this output is for
          cls:Enum|str|tuple='font-mono bg-gray-200 dark:bg-gray-800 px-2 py-1 rounded', # Additional classes
          **kwargs # Additional args for Output tag
          )->FT:
    "Styled output element for form results"
    if form: kwargs['form'] = form
    if for_: kwargs['for'] = for_  # Note: 'for' is reserved in Python
    return fh.Output(*c, cls=stringify(cls), **kwargs)

# %% ../../nbs/02_base.ipynb 4
def CodeSpan(*c, # Contents of CodeSpan tag (inline text code snippets)
             cls:Enum|str|tuple="text-sm text-primary-800 dark:text-primary-400 bg-tw-format-code-bg", # Classes in addition to CodeSpan styling
             **kwargs # Additional args for CodeSpan tag
             )->FT: # Code(..., cls='uk-codespan')
    "A CodeSpan with Styling"
    return fh.Code(*c, cls=(stringify(cls)), **kwargs)

def Code(*c, # Contents of CodeSpan tag (inline text code snippets)
             cls:Enum|str|tuple="text-sm text-primary-800 dark:text-primary-400 bg-tw-format-code-bg", # Classes in addition to CodeSpan styling
             **kwargs # Additional args for CodeSpan tag
             )->FT: # Code(..., cls='uk-codespan')
    "A Code with Styling"
    return fh.Code(*c, cls=(stringify(cls)), **kwargs)

def CodeBlock(*c: str, # Contents of Code tag (often text)
              cls: Enum | str | tuple = (), # Classes for the outer container
              code_cls: Enum | str | tuple = "'overflow-scroll max-h-full'", # Classes for the code tag
              pre_cls: Enum | str | tuple = (TextT.gray, 'bg-gray-100 dark:bg-gray-800 p-0.4 rounded text-sm font-mono'), # Classes for the pre tag
              **kwargs # Additional args for Code tag
              ) -> FT: # Div(Pre(Code(..., cls='uk-codeblock), cls='multiple tailwind styles'), cls='uk-block')
    "CodeBlock with Styling"
    return fh.Div(
            fh.Pre(Code(*c, cls=(stringify(code_cls)), **kwargs),cls=stringify(pre_cls)),
            cls=(Round.lg, stringify(cls))
        )


def P(*c, # Contents of P tag (often text)
      cls:Enum|str|tuple=PT.default, # Classes in addition to P styling
      **kwargs # Additional args for P tag
      )->FT: # P(..., cls='uk-p')
    "A P with Styling"
    return fh.P(*c, cls=(stringify(cls)), **kwargs)

def Meter(*c:FT|str, # Contents of Meter tag
          value:float=None, # Current value
          min:float=None, # Minimum value
          max:float=None, # Maximum value
          cls:Enum|str|tuple='w-full h-2 rounded', # Additional classes
          **kwargs # Additional args for Meter tag
          )->FT:
    "Styled meter element"
    if value is not None: kwargs['value'] = value
    if min is not None: kwargs['min'] = min
    if max is not None: kwargs['max'] = max
    return fh.Meter(*c, cls=stringify(cls), **kwargs)
