# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_blockquote.ipynb.

# %% auto 0
__all__ = ['BlockquoteT', 'Blockquote']

# %% ../../nbs/04_blockquote.ipynb 1
from enum import Enum
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from ..core import *
from .base import *
from .base_styles import *
from .media import Icon

# %% ../../nbs/04_blockquote.ipynb 2
def Blockquote(*c:FT|str, # Contents of Blockquote tag (often text)
               with_icon:bool=False,
               icon:FT=Icon("quote",cls=("h-8 w-8 mb-1",TextT.muted)),
               cls:Enum|str|tuple=BlockquoteT.default, # Classes in addition to Blockquote styling
               **kwargs # Additional args for Blockquote tag
               )->FT: # Blockquote(..., cls='uk-blockquote')
    "Blockquote with Styling"
    elements =[]
    if with_icon:
        elements.append(icon)
    elements.extend(c)
    return fh.Blockquote(*elements, cls=(stringify(cls)), **kwargs)
