# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_blockquote.ipynb.

# %% auto 0
__all__ = ['BlockquoteT', 'Blockquote']

# %% ../../nbs/04_blockquote.ipynb 1
from enum import Enum
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from ..core import *
from .base import *
from .base_styles import *
from .media import Icon

# %% ../../nbs/04_blockquote.ipynb 2
class BlockquoteT(VEnum):
    """Blockquote variants"""
    default = "italic font-semibold text-gray-900 dark:text-white p-4 my-4"
    solid = "italic font-semibold text-gray-900 dark:text-white p-4 my-4 border-s-4 border-gray-300 bg-gray-50 dark:border-gray-500 dark:bg-gray-800"
    secondary = "border-l-4 border-gray-300 dark:border-gray-500"
    success = "border-l-4 border-green-500"
    default_no_spacing = "italic font-semibold text-gray-900 dark:text-white"
    

def Blockquote(*c:FT|str, # Contents of Blockquote tag (often text)
               with_icon:bool=False,
               cls:Enum|str|tuple=BlockquoteT.default, # Classes in addition to Blockquote styling
               **kwargs # Additional args for Blockquote tag
               )->FT: # Blockquote(..., cls='uk-blockquote')
    "Blockquote with Styling"
    elements =[]
    if with_icon:
        elements.append(Icon("quote",cls="h-8 w-8 text-gray-400 dark:text-gray-600 mb-1"))
    elements.extend(c)
    return fh.Blockquote(*elements, cls=(stringify(cls)), **kwargs)
