# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_buttons.ipynb.

# %% auto 0
__all__ = ['BgColor', 'ButtonSize', 'ButtonOutline', 'ButtonT', 'AT', 'Button']

# %% ../../nbs/06_buttons.ipynb 1
from enum import Enum
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from ..core import *
from .base import *
from .base_styles import *

# %% ../../nbs/06_buttons.ipynb 2

# %% ../../nbs/06_buttons.ipynb 3
def Button(*c: Union[str, FT],
           cls: Enum|str|tuple=ButtonT.primary, 
           shape: Enum|str|tuple=Round.default, 
           size: Enum|str|tuple=ButtonSize.base, 
           submit=True, 
           **kwargs) -> FT: 
    base_class = "text-center inline-flex items-center"
    if 'type' not in kwargs: kwargs['type'] = 'submit' if submit else 'button'
    return fh.Button(*c, cls=(base_class, stringify(shape), stringify(cls), stringify(size)), **kwargs)
