# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/16_skeleton.ipynb.

# %% auto 0
__all__ = ['PlaceholderT', 'Placeholder']

# %% ../../nbs/16_skeleton.ipynb 1
import fasthtml.common as fh
from fasthtml.common import FT
from fastcore.all import *
from ..core import *
from .base import *
from .base_styles import *
from enum import Enum

# %% ../../nbs/16_skeleton.ipynb 2
def Placeholder(*c, # Components to put in the placeholder
                  cls:Enum|str|tuple=PlaceholderT.dashed, # Additional classes on the placeholder
                  **kwargs # Additional args for `Div` tag
                  )->FT: # Div(..., cls='uk-placeholder')
    "Creates a placeholder"
    return fh.Div(*c, cls=stringify(cls), **kwargs)
